### ISSUE TITLE
Getting DEV_HOLD device state

### ISSUE THREAD

**Issue by vladkozlov69** [Koenkk/Z-Stack-firmware#100]
Hello,

I'm trying to configure device as a coordinator using example from https://sunmaysky.blogspot.com/2017/02/use-ztool-z-stack-30-znp-to-set-up.html

However I'm getting DeviceState: DEV_HOLD:

> <TX>12:20:15.44 COM3 UTIL_GET_DEVICE_INFO (0x2700)

<RX>12:20:15.46 COM3 UTIL_GET_DEVICE_INFO_RESPONSE (0x6700)
    Status: SUCCESS (0x0)
    IEEEAddr: 0x00124B001BD814DE
    ShortAddress: 0xFFFE
    DeviceType: COORDINATOR, ROUTER, END_DEVICE (0x7)
    DeviceState: DEV_HOLD (0x0)
    NumAssocDevices: 0x00
    AssocDevicesList

**Comment by Koenkk** [comment]
For z-stack support, please refer to the TI z-stack forum.
