### ISSUE TITLE
Note about current version: CC2531_DEFAULT_20190608.zip

### ISSUE THREAD

**Issue by DerElch87** [Koenkk/Z-Stack-firmware#101]
Hi,
this is only my personal experience, but probably it can help for future versions or whatever.

For me the latest version: CC2531_DEFAULT_20190608.zip is so far the most unstable one.
In my network (17 devices with 5 routers including) I have a lot of problems with not or late reacting bulbs etc.
Sometimes I have to switch buttons many times (with about 10s waiting between) or sometimes bulbs not react at all.

I will try the max stability version today and hope that this one will work better.

Best regards.

**Comment by Koenkk** [comment]
I would recommend https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/source_routing in that case

**Comment by DerElch87** [comment]
The source routing firmware is now running since 8 days.
No issues so far, running perfectly fine.
Thank you!

**Comment by DerElch87** [comment]
And of cource,
keep on doing the good work!
Really appreciate it!
