### ISSUE TITLE
CC2530 serial port cannot send data.

### ISSUE THREAD

**Issue by LengedZhao** [Koenkk/Z-Stack-firmware#107]
When I set the file "COMPLIE.md", I found that the CC2530 serial port will send two times  restart command(FE 06 41 80 01 02 02 02 07 02 C1 ), but the other serial data cannot be sent out.

I think there are two questions . Fist, what does cause CC2530 restart? Second, why can't serial data be sent out?

When I track the reason of second problem，I find the reason is dmaCfg.txIdx[(txSel ^ 1)] is not equal 0,(_hal_uart_dma.c HalUARTWriteDMA() ,line 588). And I think because it does not enter "HalUARTIsrDMA(void)". 

Can you figure out the reason of those questions?
The Z-stack version is 3.0.2 and IAR is 10.20.1.

**Comment by Koenkk** [comment]
I think this should be moved to the TI forum, I won't maintain the firmware itself, for me it's just a location to share the firmware files and instructions on how to compile them.
