### ISSUE TITLE
Weebe cc2530_coree

### ISSUE THREAD

**Issue by Shanghaiman** [Koenkk/Z-Stack-firmware#108]
Hey, 

bought this device to have as a long range router, i have many walls between the zigbee devices and my router and signal seems to be blocked all the time.

i'm a newbe to this, and having a problem to flash and set these device (managed to do on a regular usb dongle).

can you help?
this is the device i have:
https://h-2technik.com/online/webee/ZigBee/Developkit/Zigbee_DevelopmentBoard.pdf
and there is some explanation in here but i'm not sure if it does fit zigbee2mqtt on hassio.

**Comment by ptvoinfo** [comment]
@Shanghaiman 
You may use both variants: Z-001 and Z-002. No problems.

Z-001: select a firmware for CC2530
Z-002: select a firmware for CC2530_CC2591
