### ISSUE TITLE
Credit for firmware ?

### ISSUE THREAD

**Issue by DD-NDD** [Koenkk/Z-Stack-firmware#115]
how can i credit for your firmware
_https://ptvo.info/cc2530-based-zigbee-coordinator-and-router-112/_

**Comment by Koenkk** [comment]
@ptvoinfo please check

**Comment by ptvoinfo** [comment]
@Koenkk 'Thank you' is enough :)

**Comment by ngodinhduy** [comment]
I really want your source code to adjust to UART output, and work with another MCU.

**Comment by ptvoinfo** [comment]
The router firmware contains nothing special. You may download ZStack and find several examples. I've used it too.

**Comment by ngodinhduy** [comment]
I tried, but I always got this error even though I was running in router mode, it didn't mesh so the distance was very low.
![65947715-195e0c80-e463-11e9-9ed2-77c107df54d0](https://user-images.githubusercontent.com/31593177/66027436-19bedc00-e525-11e9-9ce8-56a91ef55754.png)

**Comment by ptvoinfo** [comment]
End devices cannot provide LQI information.

**Comment by ngodinhduy** [comment]
Yes, but i  build it like Router
![66012905-36422080-e4f3-11e9-8727-0a79a3306131](https://user-images.githubusercontent.com/31593177/66095842-3f9abe00-e5c3-11e9-9185-5d4d14488423.png)

**Comment by ngodinhduy** [comment]
![66012667-38f04600-e4f2-11e9-814f-36203d646563](https://user-images.githubusercontent.com/31593177/66095918-78d32e00-e5c3-11e9-84bb-3af34188384d.png)
