### ISSUE TITLE
cc2531 router firmware not up to date

### ISSUE THREAD

**Issue by arneman** [Koenkk/Z-Stack-firmware#116]
Hi,

the firmware in your repo (https://github.com/Koenkk/Z-Stack-firmware/tree/master/router/CC2531/bin) is not up to date. ptvo released a newer version in february 2019. It is a little bit confusing (wordpress url structure), but here you'll find the current ptvo firmware from 2019/02 for cc2531: 
 http://ptvo.info/wp-content/uploads/2018/09/cc2531_1.2.2a.44539_firmware.zip

Maybe you can update your repo?

Regards

Arne

**Comment by Koenkk** [comment]
Done!
