### ISSUE TITLE
[Feature request] Stack for simple sensor

### ISSUE THREAD

**Issue by pedroke** [Koenkk/Z-Stack-firmware#117]
I think many newbies would welcome a possibility to implement their own end node (sensor) for testing purposes. Would it be possible to provide an example implementation of z-stack firmware with minimal end node code, serving e.g. as a simple demo sensor (e.g. on/off switch)... I'm not familiar with z-stack API and it is kind of hard to grasp for beginner and such example end node would be a great showcase which could be further extended and developed into many different custom zigbee nodes.. Is there any similar project already available?

**Comment by imdos** [comment]
Yes search for/have a look at pvto.switch and DiYruz or something closely to this (it is mentioned in the 1.6.0 release logs AFAIK).
