### ISSUE TITLE
SONOFF BASICZBR3 - A new pre-built router?

### ISSUE THREAD

**Issue by marrold** [Koenkk/Z-Stack-firmware#125]
Sonoff have released the BASICZBR3, a Zigbee device based on the CC2530 - https://www.youtube.com/watch?v=yFwJAQFndEo

Assuming the pins are exposed to program it, this could make a nice "pre-built" router

**Comment by ptvoinfo** [comment]
Yes, but it would be great to have a chip with an amplifier there.

**Comment by marrold** [comment]
Seems like the Zigbee range / performance is actually fairly disappointing.

**Comment by drogfild** [comment]
Off topic: is it even worth buying for a Zigbee switch?

**Comment by marrold** [comment]
> Off topic: is it even worth buying for a Zigbee switch?

It's cheap and it works. RF performance is probably good enough for an End Device assuming you have reasonable network coverage. It's just not quite good enough to expand signal coverage as a router, but in fairness that's not the devices intention.

**Comment by Gamester17** [comment]
FYI, kirovilya has released Z-Stack 3.0 firmware/source with Zigbee 3.0 support for Sonoff BASICZBR3.

Please see related request/discussion -> https://github.com/Koenkk/Z-Stack-firmware/issues/176
