### ISSUE TITLE
Using CC2530+CC2591 as a router - which pins are used for UART ? 

### ISSUE THREAD

**Issue by marrold** [Koenkk/Z-Stack-firmware#127]
I'm considering using one of these [CC2530+CC2591](https://www.ebay.co.uk/itm/Anti-interference-TI-CC2530-CC2591-UART-ZigBee-Module-Wireless-w-2-4G-Antenna/163827817866) devices as a ~~router~~ coordinator.

I can find the firmware in this repo, but it doesn't document which of the CC2530s pins are used for the UART interface. I did find [this comment](https://github.com/Koenkk/zigbee2mqtt/issues/52#issuecomment-390658072) - is it still relevant? 

Thanks

**Comment by ptvoinfo** [comment]
@marrold The mentioned router firmware does not support the UART interface.

**Comment by marrold** [comment]
@ptvoinfo Yes my mistake, I meant a coordinator. 

Thanks

**Comment by ptvoinfo** [comment]
Coordinator: P02, P03, GND

**Comment by marrold** [comment]
Thanks!
