### ISSUE TITLE
XDATA

### ISSUE THREAD

**Issue by HKC001** [Koenkk/Z-Stack-firmware#13]
For instruction 9 of [compiling optimised CC2530 firmware](https://github.com/Koenkk/Z-Stack-firmware/tree/optimize/coordinator/CC2530_CC2591), do we need to change XDATA for both Stack sizes and Heap sizes?

**Comment by Koenkk** [comment]
Only for the stack (heap XDATA should be `0x00`)

**Comment by HKC001** [comment]
Thanks!
