### ISSUE TITLE
[REQUEST] Z-Stack 3.0.x router firmware for CC2530 and CC2531?

### ISSUE THREAD

**Issue by Hedda** [Koenkk/Z-Stack-firmware#153]
@Koenkk Any chance that you could release Z-Stack 3.0.x router firmware hex bin files for CC253x?

https://github.com/Koenkk/Z-Stack-firmware/tree/master/router

That is, base a router firmware for CC253x on Z-Stack 3.0 instead of Z-Stack Home 1.2 protocol stack?

http://www.ti.com/tool/Z-STACK-ARCHIVE

The reason is that that many users are now asking if it is possible to use cheap CC2530 and/or CC2531 hardware as fully compliant Zigbee 3.0 router hardware in a Zigbee 3.0 network.

I know that a ZHA 1.2 router can already be used in Zigbee 3.0 networks, and I also understand that many (if not most) devices can run in ZHA 1.2 backwards-compatibility mode, but I believe that those Zigbee 1.2 routers are then limited to only route the ZHA 1.2 (Zigbee Home Automation) protocol/profile and not other Zigbee 3.0 and Zigbee PRO protocols/profiles (i.e. the full Zigbee 3.0 protocol stack), also known by their different "Zigbee Application Profiles" names.

Hence requesting capability to be a fully compliant Zigbee 3.0 router, inc. for protocols/profiles like:

- Zigbee Home Automation (ZHA)
- Zigbee Light Link (ZLL) 2.0
- Zigbee Remote Control (ZRC) 2.0
- Zigbee Building Automation (ZBA)
- Zigbee Retail Services (ZRS)
- Zigbee Health Care (ZHC)
- Zigbee Telecommunication services (ZTS)

As you probably all already know, the new Zigbee 3.0 standard is a variation to previous Zigbee standards that are referred to as "Zigbee Application Profiles". The important outtake from this is that the Zigbee 3.0 specification enables interoperability among those different "Zigbee Application Profiles". Due to this, Zigbee 3.0 allows devices from different application areas to communicate and form single homogeneous network, including allowing Zigbee 3.0 devices to act as a router for other Zigbee 3.0 devices that are using a different "Zigbee Application Profile". For example, device#1 from Zigbee Light Link profile can coexist with device#2 from Zigbee Health Care profile with same Zigbee 3.0 network. Zigbee 3.0 provides backward compatibility with other Zigbee application profiles such as Zigbee Light Link 1.0 profile, Zigbee Home Automation 1.2 profile, etc. and more.

Is it even possible to use CC2530/CC2531 hardware as a Zigbee 3.0 router with TI Z-Stack 3 firmware?

I understand that CC253x based hardware is not recommended by Zigbee2mqtt developers to use as a Zigbee 3.0 coordinator hardware as the MCU in those chips might not be powerful enough to run the TI Z-Stack 3 coordinator firmware without performance-related issues. However, might not CC253x based hardware be good enough to in most cases be used as fully Zigbee 3.0 compliant router devices if they could run TI Z-Stack 3?

Could example the Z-Stack 3.0.x coordinator firmware for CC253x be ported into a router firmware?

https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator

That is, is it possible to change the TI Z-Stack 3 firmware from coordinator config to router config?

**Comment by Hedda** [comment]
Maybe this request should go to ptvo @ptvoinfo who looks to be credited for existing router firmware?

**Comment by ptvoinfo** [comment]
@Hedda There are no advantages of ZStack3 in home environments. Therefore I didn't plan to create a router firmware based on ZStack3.

**Comment by Hedda** [comment]
I know that there were no real advantages before today as practically all devices sold for home use used either the ZHA 1.2 or ZLL 1.0 profiles and most devices that used the ZLL profile are also backwards-compliant with the ZHA 1.2 profile, but now more and more Zigbee devices are coming to market that is fully compliant with Zigbee 3.0 certified products and also newer Zigbee coordinator hardware/chips that are fully Zigbee 3.0 compatible.

https://zigbeealliance.org/product_type/certified_product/

Zigbee Alliance also only certify devices that are fully Zigbee 3.0 compliant.

**Comment by dzungpv** [comment]
It not possible, TI not update SDK for CC2530/2531/2538 devices to 3.x

**Comment by Hedda** [comment]
@dzungpv it is too possible. You are right that TI will not officially release Z-Stack 3.x SDK for older chips like CC2530/2531/2538 but independent developers have already backported Z-Stack 3.x firmware to older chips like CC2530/2531/2538 as you can see here https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator

Again it is true that Koenkk is not recommending running CC2530/2531/2538 hardware as a Zigbee 3.0 coordinator in an production environment because of performance issues, but using Z-Stack 3.x firmware as a switch and router firmware on CC2530/2531/2538 hardware might not have the same performance issues are running Z-Stack 3.x coordinator firmware.

**Comment by dzungpv** [comment]
> @dzungpv it is too possible. You are right that TI will not officially release Z-Stack 3.x SDK for older chips like CC2530/2531/2538 but independent developers have already inofficially backported Z-Stack 3.x firmware to older chips like CC2530/2531/2538 as you can see here:
> 
> https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator
> 
> Again it is true that @Koenkk is not recommending running CC2530/2531/2538 hardware as a Zigbee 3.0 coordinator in a production environment because of performance issues, but using Z-Stack 3.x firmware as a switch and router firmware on CC2530/2531/2538 hardware might not have the same performance issues are running Z-Stack 3.x coordinator firmware.

It is 3.0.x not 3.x. No dev could backport it, because it is close sourced both in firmware and asic level. You can read  Readme in that respo. Simpler solution, just bought cc1352/cc2652 to use 3.x

**Comment by Hedda** [comment]
OK my mistake typing 3.x when I meant 3.0.x to get Zigbee 3.0 router support on CC2530/2531/2538

**Comment by fi-sch** [comment]
I would be so glad if @Koenkk would make a router firmware for cheaper cc modules. I personally use a few of cc2530+cc2591 so it would be great to be able to use Z-Stack 3.0 as I add more and more devices to my network.

**Comment by Gamester17** [comment]
@kirovilya any chance you are willing to make a Z-Stack 3.0 router firmware for CC2530 and CC2531?

* https://github.com/Koenkk/Z-Stack-firmware/tree/master/router

Just considering that you seem to be the only one who has made Z-Stack 3.0 run on CC253x or?

* https://github.com/diyruz/diyruz_rt

* https://habr.com/ru/company/iobroker/blog/495926/

**Comment by Hedda** [comment]
Please unstale as I still think quite a few people would like to try Z-Stack 3 router firmware on CC2530 and CC2531 USB dongles.
