### ISSUE TITLE
Coordinator firmware for CC2538+2592

### ISSUE THREAD

**Issue by zslibra** [Koenkk/Z-Stack-firmware#160]
I am trying to assemble a USB stick using CC2538+2592 (MODKAMRU Zigbee V3) for coordinator.
I have downloaded the firmware CC2538_CC2592_MODKAMRU_V3_20200327.zip from
https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.0.x/bin
I got 3 firmwares after unzip the zip file.
MODKAMRU_V3_UART-flow-control.hex, MODKAMRU_V3_UART-no-flow-control.hex, MODKAMRU_V3_USB.hex
Which firmware should I use for zigbee2mqtt?
Thanks.

**Comment by kirovilya** [comment]
for USB-stick use MODKAMRU_V3_USB.hex

**Comment by zslibra** [comment]
Understood.
Thanks kirovilya!
