### ISSUE TITLE
How to make the firmware suitable for the PA rfx2401c

### ISSUE THREAD

**Issue by zrainx** [Koenkk/Z-Stack-firmware#161]
Hi Koenkk ,  
    I have a zigbee device  the hardware is PA rfx2401c + CC2530.  
    But I don't know how to fit the Z-Stack_Home_1.2 (default)  for the hardware.
   Would you kindly give me some advice?
   Thank you.

**Comment by Koenkk** [comment]
I don't provide direct support for building own firmware, please consult the TI forum: https://e2e.ti.com/
