### ISSUE TITLE
Use CC1352P-2 like router 

### ISSUE THREAD

**Issue by ozer59** [Koenkk/Z-Stack-firmware#169]
How to process to use CC1352P-2 like a router 

I have 2 CC1352P-2 1 for Coordinator i want use the second like routeur 
i try this firmware :https://github.com/Koenkk/zigbee2mqtt/issues/1429#issuecomment-581177622

 but i don't know how to process to pair it

**Comment by Koenkk** [comment]
Currently there is no router firmware available. @ptvoinfo are you interested in building it?

**Comment by ozer59** [comment]
yes a lot a need to extend my network because legrand router won't work with xiaomi devices sensor detector ...

**Comment by ptvoinfo** [comment]
I don't have such a device and development tools for ARM. I cannot do it right now.

**Comment by Koenkk** [comment]
@ptvoinfo would you be interested in building when we send you a CC2652R for free? (building tools are free btw)

**Comment by ptvoinfo** [comment]
@Koenkk Sorry, it may take months.

**Comment by gcormier** [comment]
Is the CC26x2R in the same situation? (No router support for unknown amount of time?)

**Comment by asciidisco** [comment]
Is there any way to sponsor or support this?
I'm currently running a LAUNCHXL-CC26X2R1 coordinator & have 2 CC2531 running as routers & they don't really cut it. With 2 zig-a-zig-ah! devices sitting on my desk, I'm currently facing the decision to break my net up into 3 seperates ones (which I believe will come with a few other problems)...

So yeah, I'd be up for sponsoring this cause or support it as developer if there's something I can do.

**Comment by gcormier** [comment]
I'd pitch in some money for router support for 1352P/CC2652R.

**Comment by Pascal51882** [comment]
Is there still no firmware? For really big range networks it would be great :)
