### ISSUE TITLE
Does Z-Stack-firmware support hardware of cc2530+2590 (PA) ?

### ISSUE THREAD

**Issue by zrainx** [Koenkk/Z-Stack-firmware#170]
Hi Koenkk,
     I have a zigbee dongle consists of cc2530+2590 (PA). 
     Does Z-Stack-firmware support it?
     Thanks a lot.

**Comment by ptvoinfo** [comment]
@zrainx Do you mean a coordinator or a router firmware?

**Comment by zrainx** [comment]
@ptvoinfo A coordinator firmware.

**Comment by ptvoinfo** [comment]
The corresponding firmware exists in the repository.
