### ISSUE TITLE
CC1352P-2 turn off led's

### ISSUE THREAD

**Issue by a-bailey** [Koenkk/Z-Stack-firmware#180]
Sorry if this is a stupid question but I'm no hardware guy, can I turn off the CC1352P-2 power led by removing the led jumpers? I'd like to turn all led's off since the antenna is in a cupboard anyway so it just wastes power. I couldn't really find it in the documentation and I already killed one board by mistake.

**Comment by marc-gist** [comment]
did you try the configuration `disable_led: true` under `serial` in the configuration?
https://www.zigbee2mqtt.io/information/configuration.html

otherwise, who cares. an LED will draw maybe  a couple mA of power on a powered device.
