### ISSUE TITLE
Best firmware for cc2538 +cc2592

### ISSUE THREAD

**Issue by SamuelCarson** [Koenkk/Z-Stack-firmware#182]
Many different firmware version are available.Very confusing.  Which is latest for MODKAM.RU V3 coordinator by Jager???

# Bug Report
## Debug Info
Zigbee2mqtt version:
Adapter hardware: CC2531, CC2530, CC26X2R1 or CC1352P-2
Adapter firmware version:
cc2538 + cc2592

**Comment by Koenkk** [comment]
@reverieline could you take a look?

**Comment by reverieline** [comment]
> Many different firmware version are available.Very confusing. Which is latest for MODKAM.RU V3 coordinator by Jager???

The olny difference is connection interface.
MODKAMRU_V3_USB.hex for USB connected devices.
MODKAMRU_V3_UART-no-flow-control.hex for 4-wire UART connection (VCC,GND,TX,RX).
MODKAMRU_V3_UART-flow-control.hex for 6-wire UART connection (VCC,GND,TX,RX,RTS,CTS).

**Comment by SamuelCarson** [comment]
I had found these and they seemed to be to latest versions. BUT there a many others referred to in the CC2538 discussions. I just wanted to be sure these were the latest available.  Thanks
