### ISSUE TITLE
E18-MS1PA1-PCB Does not work after flashing (CC2530+CC2592)

### ISSUE THREAD

**Issue by dstasiuk** [Koenkk/Z-Stack-firmware#186]
Hi guys.
This EBYTE E18-MS1PA1-PCB module does not work after flashing. 
I try 2 different modules and the result is the same - after reflashing, it does not start.
Connected GND, 3.3V, P2.1, P2.2, RST, successfully flash, and pass the verify.
RX, TX (P0.2,P0.3) **does not respond** - using oscilloscope.
Maybe I connected something wrong?
![image](https://user-images.githubusercontent.com/12288518/86037334-e378a380-ba47-11ea-9e40-b79a0dedc4ec.png)

**Comment by dstasiuk** [comment]
I need connect P2.0 to GROUD?

**Comment by codmpm** [comment]
Hey @dstasiuk,

here's the wiring of my [E18-MS1PA1-IPX Raspberry Pi UART Adapter](https://shop.codm.de/automation/zigbee/15/zigbee-long-range-raspberry-pi-funkmodul-v0.3).

![wiring-pi-e18-ms1pa1-ipx](https://user-images.githubusercontent.com/9745239/86790862-2ac6eb80-c069-11ea-91c5-bfaee30a220a.png)

P0.2 is RDX, thus TXD on the Pi
P0.3 is TXD, thus RXD on the Pi

Only VCC and GND are needed for the function. 
For programming you DC/DD, which are P2.2/P2.1, as well as RST, GND and VCC.

I flashed CC2530_CC2592_20190523.zip from https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.0.x/bin for Z-Stack 3.0.x or CC2530_CC2592_DEFAULT_20190608.zip from https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/default as a coordinator.

Cheers,
Patrik
