### ISSUE TITLE
patch failed

### ISSUE THREAD

**Issue by flower87lucky** [Koenkk/Z-Stack-firmware#190]
$ git apply --check firmware.patch
warning: znp_CC1352P_2_LAUNCHXL_tirtos_ccs/cc13x2lp.cmd has type 100644, expected 100755
error: patch failed: znp_CC1352P_2_LAUNCHXL_tirtos_ccs/znp.syscfg:52
error: znp_CC1352P_2_LAUNCHXL_tirtos_ccs/znp.syscfg: patch does not apply
warning: znp_CC2652RB_LAUNCHXL_tirtos_ccs/cc26x2lp.cmd has type 100644, expected 100755
error: patch failed: znp_CC2652RB_LAUNCHXL_tirtos_ccs/znp.syscfg:50
error: znp_CC2652RB_LAUNCHXL_tirtos_ccs/znp.syscfg: patch does not apply
warning: znp_CC26X2R1_LAUNCHXL_tirtos_ccs/cc26x2lp.cmd has type 100644, expected 100755
error: patch failed: znp_CC26X2R1_LAUNCHXL_tirtos_ccs/znp.syscfg:49
error: znp_CC26X2R1_LAUNCHXL_tirtos_ccs/znp.syscfg: patch does not apply

**Comment by Koenkk** [comment]
Make sure your source is clean (without changes), add `--ignore-space-change` and make sure you are using SIMPLELINK-CC13X2-26X2-SDK_4.10.00.78.
