### ISSUE TITLE
CC2538 + CC2592 Issues

### ISSUE THREAD

**Issue by michalszymura** [Koenkk/Z-Stack-firmware#192]
So i just flashed CC2538 + CC2592 with CC2538_CC2592_MODKAMRU_V3.
I'm on dev branch of zigbee2mqtt
I discovered that after the device looses power it's unable to reconnect to any of my bulbs. Weirdly hue remote works fine(edit: remote directly connected to the coordinator not bulbs).
I have to repair all the bulbs. Not sure what's the problem.

Steps to reproduce 
- stop the container
- unplug the stick
- plug the stick back
- start the container

Could it be because I set pan id and extended pan id myself?
I will try without it in the morning and report back.

**Comment by michalszymura** [comment]
I can confirm same behaviour after removing pan id and extended pan id, removing all databases and re-flashing the stick. Not sure what else i could try?

**Comment by michalszymura** [comment]
It somehow started working properly when i tried starting container without stick plugged in and then with stick plugged in it reconnected to everything.

**Comment by kirovilya** [comment]
@michalszymura try previous version firmware (20200211) https://github.com/reverieline/CC2538-CC2592-ZNP/tree/967b3b0ce3302a2dda1ec6f4cd181c0f086dda01

**Comment by michalszymura** [comment]
The older firmware works fine.
