### ISSUE TITLE
flash error

### ISSUE THREAD

**Issue by zoral566** [Koenkk/Z-Stack-firmware#2]
atti@debian:~/cc-tool$ sudo ./cc-tool -e -w CC2531ZNP-Prod.hex 
  Error occured: File 'CC2531ZNP-Prod.hex' load error: Record header not found, line: 7

Windows flasher: could not open specified HEX file

**Comment by Koenkk** [comment]
Whats the output of `cat CC2531ZNP-Prod.hex`?

**Comment by zoral566** [comment]
the problem was the wrong download. It was several times worse, and finally it did. Thank you for taking care of me.

**Comment by Koenkk** [comment]
Good 😄
