### ISSUE TITLE
std or diag?

### ISSUE THREAD

**Issue by prankousky** [Koenkk/Z-Stack-firmware#207]
Hello,

the `router-cc2531*.hex` has three different versions (diag-usb, diag, std), and the `router-cc2530*.hex` has diag and std.

Are the `diag` versions **only** for debugging, or, in other words: should one always use the `std` versions? Or does it not matter? I just added three routers (2x CC2530, 1x CC2531) to my network. Both CC2530 run on `diag` and produce quite some mqtt traffic. Is this fine? Or does producing all this traffic also limit their performance so that I should flash the `std` ones?

Thank you :)

**Comment by Koenkk** [comment]
Use std for production, it produces less zigbee traffic than the diag ones.

**Comment by prankousky** [comment]
Thank you :)
