### ISSUE TITLE
sourcecode

### ISSUE THREAD

**Issue by fensoft** [Koenkk/Z-Stack-firmware#21]
Hello,

Is there any way to compile the firmware ourselves ?
Where can we find the sourcecode of coordinator and router ?

Thanks !

**Comment by Koenkk** [comment]
https://github.com/Koenkk/Z-Stack-firmware/blob/master/README.md

**Comment by fensoft** [comment]
so for the router this is just the pure ti's z-stack 1.2.2a "router" firmware ?

**Comment by fensoft** [comment]
ok, thanks.

for all those who are searching, looks like a good start for the router sourcecode:
http://ptvo.info/cc2530-based-zigbee-coordinator-and-router-112/
