### ISSUE TITLE
0-10volt

### ISSUE THREAD

**Issue by LuukML** [Koenkk/Z-Stack-firmware#213]
Hi Koen,

i cold not find a emaild adres so thout to send it heer, if this is not the place let me know!

I am currently trying to find en zigbee divice where I have 2 outputs 1. (0-10v output dimmable output) 2. (0-10v output with on off option.) I would prefer to control these outputs via a standard on / off dimmer button from example sunricher. Binding in case the gateway falls out, I can still operate the lamps. I try to make a zigbee lamp myself. I currently have a lamp where I can already control the led drivers and leds via my old setup 0-10v. But I would like to convert this to zigbee.

Is this something you think can be made with the help of a cc2530?

would be great if you could help me on my way as im new to coding and new to zigbee :D

**Comment by Koenkk** [comment]
I'm not sure, but this might be possible with: https://ptvo.info/zigbee-configurable-firmware-features/
