### ISSUE TITLE
CC2530+CC2592 as router

### ISSUE THREAD

**Issue by Boia11** [Koenkk/Z-Stack-firmware#215]
Hi!
What firmware should I use for CC2530+CC2592? Why there is no specific firmware?

**Comment by Koenkk** [comment]
Added, you can use https://github.com/Koenkk/Z-Stack-firmware/tree/master/router/CC2530_CC2592/bin

**Comment by beppexx80** [comment]
@Koenkk hi, i have the CC2530+CC2592, which firmware should i install?
