### ISSUE TITLE
Updating firmware

### ISSUE THREAD

**Issue by Dutchy-79** [Koenkk/Z-Stack-firmware#219]
HI,

Can I update the firmware of my coordinator and router,
If possible, How to please.

Regards,

Dutchy

**Comment by hqas** [comment]
What hardware are you running ?
If you are using a CC2531 just follow https://www.zigbee2mqtt.io/information/flashing_the_cc2531.html

**Comment by Dutchy-79** [comment]
That's what I followed, should have mentioned that indeed.

Just wondering if that's the latest version available.
