### ISSUE TITLE
remove device while device trying to join insecurely

### ISSUE THREAD

**Issue by Arminhosseini** [Koenkk/Z-Stack-firmware#224]
I have a problem related to cc2530 firmware. 
when some devices trying to join many times they try to join with an insecure update device so the coordinator sending remove device and force the device to leave so I searched that issue in the TI forum and find it's problem is like below:
occurs if BDB_DEFAULT_TC_REQUIRE_KEY_EXCHANGE is set to TRUE and pre-Zigbee 3.0 Spec devices attempt to join without sending a TCLK update.
and I want to ask you could you please change cc230 firmware that has been used for zigbee2mqtt coordinator so it let's insecure joining.
regards.

**Comment by Koenkk** [comment]
I've checked but this is already set to `FALSE`:

![image](https://user-images.githubusercontent.com/2892853/97217070-01240280-17c7-11eb-8c0f-c0f4cfcb347c.png)

As TP2_LEAGCY_ZC is defined (https://github.com/Koenkk/Z-Stack-firmware/blob/f2a7aa17fba716c72dd46d4821328f7daeb1e238/coordinator/Z-Stack_3.0.x/firmware_CC2531_CC2530.patch#L195)

**Comment by Arminhosseini** [comment]
ok, I will check this patch and I will let you know.
thank's

**Comment by Arminhosseini** [comment]
oooh, I'm not using z-stack3 I'm using zstack ha 1.2

**Comment by Koenkk** [comment]
1.2 does not have `BDB_DEFAULT_TC_REQUIRE_KEY_EXCHANGE`
