### ISSUE TITLE
Coordinator firmware device limits

### ISSUE THREAD

**Issue by fensoft** [Koenkk/Z-Stack-firmware#23]
Hello,

What's the limit of the 3 firmwares found in the sourcecode ?
[Here](https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/CC2531/alternatives/max_devices) is written: ~16 devices and ~16 routers for the classic version and 44 devices and 1 router for the alternate version on a single CC2531

If I understand well:
NWK_MAX_DEVICE_LIST = number of total devices
MAX_NEIGHBOR_ENTRIES = number of routers

Questions:
Does a router connected to another router counts as a neighbor (indirect neighbor)?
Does a router counts as a device ?

**Comment by Koenkk** [comment]
The normal firmware (which I highly recommend) has support for 15 **direct** nodes. 

I hope this picture explains your question:

![image](https://user-images.githubusercontent.com/2892853/50925446-a20ac780-1452-11e9-9e1e-9a4a527c49e4.png)

**Comment by fensoft** [comment]
Oh, my god. Thanks for a such clear explaination :)

How many total devices does it manage ? Virtualy unlimited ?

**Comment by Koenkk** [comment]
@fensoft Hard to say, various users have reported that 50 nodes works without problems, I don't have any reports above that (I expect it to work though).

**Comment by fensoft** [comment]
Thanks !

So, in the memory of the coordinator, the list of direct devices are stored in the devices but not the ones behind a router ? So, the router have it's own list of devices ?

**Comment by Koenkk** [comment]
@fensoft yes and yes.

**Comment by leobel96** [comment]
Sorry for the intrusion but do all the light bulbs act as routers? If yes, can a person add as many light bulbs as he wants ?

**Comment by fensoft** [comment]
How does the other devices change their path ? Can we set a device to use a specific router ?

**Comment by leobel96** [comment]
In my opinion it would be useful to add the device type near each device in this page https://koenkk.github.io/zigbee2mqtt/information/supported_devices.html.

**Comment by Koenkk** [comment]
@fensoft The zigbee protocol takes care of this.

**Comment by p33k** [comment]
I connected 21 devices (all xiaomi sensors, and switches, no routers) with my CC2531 stick using iobroker zigbee. 22th device won't connect.
Does 21 make sence in any way?
I bough some osram smart plugs to use them as routers and add more devices, but even when I deleted some sensors the smart plugs don't connect.
Do I have to flash the usb stick again and start all over?
