### ISSUE TITLE
Add intergace GUI to update FW

### ISSUE THREAD

**Issue by pepsonEL** [Koenkk/Z-Stack-firmware#231]
Hi
Is any chance to add any GUI to simply update FW ? I think about uptade coordinator. I use this device:
https://www.tindie.com/products/slaesh/cc2652-zigbee-coordinator-or-openthread-router/?fbclid=IwAR17G1jbB29tIIZdl3-_0tVi9PzjAO2JPeN2GXPPVl39snhpYeYRhurUL6M

**Comment by bigretromike** [comment]
Would be a nice thing for sure.

**Comment by samsam-rolon** [comment]
Very Intrested in ! I have a cc2530 and cc2531 and my CC2530 router (as range extender) is not easily flashable du to how I have rack it and the limited access to the PINs.
