### ISSUE TITLE
Z-Stack firmware 20190223 Zigbee 3.0 devices

### ISSUE THREAD

**Issue by alexair777** [Koenkk/Z-Stack-firmware#239]
Hello,

At the moment I am using the Z-Stack 1.2 firmware 20190223 with a CC2531 as coordinator.
Is it possible to use Zigbee 3.0 devices with this kind of firmware? Or do I need to upgrade to the Z-Stack 3 coordinator firmware? If I will upgrade to this version, will the old Zigbee 1.0, 2.0 devices still work?
I would like to use the new Aqara Single Switch Module T1 (No Neutral) SSM-U02 with Zigbee 3.0 together with the old Zigbee devices.

Thanks a lot!

Best regards

**Comment by Koenkk** [comment]
Yes, you can use 1.2 devices on a 3.0 coordinator and vice versa.
