### ISSUE TITLE
Source for CC2531 router

### ISSUE THREAD

**Issue by Astiolo** [Koenkk/Z-Stack-firmware#245]
Hi, I'm trying to use a CC2531 to create my own zigbee smart device/router. I've got the TI Z-Stack 3.0.2, but it appears to be built around the development board with LCD and other buttons. I like the way your router firmware works and would like to add a couple of simple control options to it.

Is there a chance you could make the code or just the relevant changes available?

**Comment by Koenkk** [comment]
@Astiolo I don't have the source of this, firmwares are from: https://ptvo.info/cc2530-based-zigbee-coordinator-and-router-112/
