### ISSUE TITLE
Where can I get the firmware source code？

### ISSUE THREAD

**Issue by CaptainNeil** [Koenkk/Z-Stack-firmware#246]
CC2531 coordinator/router source code.
CC26X2R1 coordinator source code.

**Comment by Koenkk** [comment]
- CC2531 coordinator: https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_Home_1.2/COMPILE.md
- CC26X2R1 coordinator: https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.x.0/COMPILE.md
- CC2531 router: firmware is only hosted here, it's taken from https://ptvo.info/cc2530-based-zigbee-coordinator-and-router-112/ . No source code has been made available by the creator.
