### ISSUE TITLE
Source routing for CC1352P_2?

### ISSUE THREAD

**Issue by sascha777** [Koenkk/Z-Stack-firmware#248]
Hi all,

I am running z2m (latest version) for 2 years now using a CC1352P_2 (also latest image) since a year or so. 
With adding some more Xiaomi devices I now run about 53 devices in the current setup. 

Sometimes a device looses the connection. When I rejoin the device it seems to kick another device out. 

I think this is due to the Zigbee 3.x Coordinator direct connection limit to 50 devices. In my network there are several ac powered devices that could be used als routers (what the already do now). 

I read about the source routing for the coordinator. Is this available for the CC1352P_2, too? I didn't find any images nor a description of how to enable source routing when compiling the image from source.

Thanks

**Comment by Koenkk** [comment]
All firmwares for the CC1352/CC2652 devices have source routing enabled.

**Comment by sascha777** [comment]
I am confused as the network map shows about 10 end devices directly connected to the coordinator. 
To my understanding source routing would only allow 5 direct devices.
Do I have to enable this by config then?

**Comment by Koenkk** [comment]
That's only for the CC2531, CC1352 allows 50: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator

**Comment by sascha777** [comment]
Thanks for clarifying ✅
