### ISSUE TITLE
CC2652R Flashed but wont pair

### ISSUE THREAD

**Issue by jimmyeao** [Koenkk/Z-Stack-firmware#249]
Hi, fantastic to see router firmware for the CC2652, however, after flashing i am unable to pair it with my CC2531 coordinator (ZAigbee2mqtt) Nothing appears in the logs of Zigbee2mqtt.

How could I troubleshoot this?

Thanks :)

**Comment by Koenkk** [comment]
- Did you click the button your CC2652 and wait 20 seconds after that?
- If that doesn't work sniff the traffic while trying to join: https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html

**Comment by jimmyeao** [comment]
Reflashed and clicked (I think I was missing the single click after flashing) and it has now paired, thanks :)

**Comment by Theminijohn** [comment]
Which button was that @jimmyeao ?

**Comment by jimmyeao** [comment]
The button on the stick, I use this one https://electrolama.com/projects/zig-a-zig-ah/
