### ISSUE TITLE
Router firmware without/with configurable LED

### ISSUE THREAD

**Issue by ohrensessel** [Koenkk/Z-Stack-firmware#25]
Currently, the LED of the router is blinking during normal operation. This might get quite annoying depending on where the stick is operating. For the coordinator, zigbee2mqtt offers a handy option to disable the LED.

Would it be possible to disable the LED on the router as well, e.g. by a long press on SW1 or so?

**Comment by Koenkk** [comment]
@ptvoinfo is this possible?

**Comment by ptvoinfo** [comment]
Currently, the router blinks when it sends the "onOff" state to the coordinator. It is possible to disable this report through the config command. Below is the example, but I don't know how to implement this in the latest version of zigbee2mqtt.

```
function configure_report_interval(dev) {
    'use strict';

    if (!dev) {
        return;
    }

    var info = shepherd.info();
    if (info.joinTimeLeft) {
        setTimeout(configure_report_interval, info.joinTimeLeft * 1000, dev);
        return;
    }

    var sendCB = function (err) {
        if (err) {
            console.log('Unable to configure reporting:', get_device_desc(this.device), 'Err:', err);
        }
    };

    var cId = 'genOnOff';
    var attrId = 'onOff';
    var reportIntervalSec = 60; // 65535 - disables the report at all
    var epId, ep;
    for (epId in dev.endpoints) {
        ep = dev.endpoints[epId];
        if (ep.clusters.hasOwnProperty(cId)) {

            console.log('Sending config report to:', get_device_desc(dev.ieeeAddr));
            ep.report(cId, attrId, reportIntervalSec, reportIntervalSec ,
                sendCB.bind({
                    device: dev.ieeeAddr
                }));
            break;
        }
    }
}
```

**Comment by ohrensessel** [comment]
Is this report in any way associated with the link quality and online/offline status reported via MQTT?

I'm referring to the data which is displayed in my homeassistant installation like this:

![image](https://user-images.githubusercontent.com/775756/50967535-b0032b80-14d8-11e9-92e9-daaa250f60bb.png)
![image](https://user-images.githubusercontent.com/775756/50967636-f3f63080-14d8-11e9-856f-68aae1b7f95f.png)

Link quality seems to work well, but the router is always displayed as offline (as you can see in the second image). But this maybe is something for a different issue?

**Comment by ptvoinfo** [comment]
@ohrensessel The router reports the state value, but this value is not related to the offline/online state.

**Comment by d1slact0r** [comment]
how do I disable the led of the coordinator firmware on my usb stick?

**Comment by ohrensessel** [comment]
Via the disable_led config option (see
https://koenkk.github.io/zigbee2mqtt/configuration/configuration.html)

Am Mi., 23. Jan. 2019, 23:44 hat d1slact0r <notifications@github.com>
geschrieben:

**Comment by sonntam** [comment]
@ptvoinfo I tried the following command

```
{
    "devId": "zigbee.0.00124b001936aa9b",
    "ep": "8",
    "cid": "6",
    "cmd": "6",
    "cmdType": "foundation",
    "zclData": {
        "attrId": "0",
        "minRepIntval": "65535",
        "maxRepIntval": "65535",
        "direction": "0"
    }
}
```

but it didn't work. The LED is still blinking. Am I missing something?

**Comment by ptvoinfo** [comment]
@sonntam Is the endpoint number correct? Also, it should be "report-config" command.

**Comment by sonntam** [comment]
The cmd-id no. 6 corresponds to "configReport" so I think it should be correct. I also tried endpoint no. 0 to no avail.

**Comment by furiaceka87** [comment]
Are you able to disable the red blinking led for the router?

**Comment by sonntam** [comment]
@furiaceka87 I wasn‘t able to disable the blinking yet. My WAF is really bad right now 😭 
I‘m still hoping for some help.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
