### ISSUE TITLE
Flashed the router CC2652RB_1.0.0.zip not acknowledge by zigbee2mqtt

### ISSUE THREAD

**Issue by HVPereira** [Koenkk/Z-Stack-firmware#250]
Hello I've Flashed the new CC2652RB onto my slaesh pen.

It is beeing able to be discovered on zigbee2mqtt however it states is unsupported as seen below:

![image](https://user-images.githubusercontent.com/5346125/106147656-08fd9500-6170-11eb-8b89-051c44f6567a.png)

![image](https://user-images.githubusercontent.com/5346125/106147720-1f0b5580-6170-11eb-8d22-e07ce91f13ca.png)

Not sure if i can show anything else.. but guide me to how i can support here.

**Comment by Koenkk** [comment]
It's only supported in the latest dev branch. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
