### ISSUE TITLE
Two set of ZCDs(CC2530) not working when both are placed closer

### ISSUE THREAD

**Issue by JPavithran** [Koenkk/Z-Stack-firmware#255]
Hi, 

I using CC2530_CC2591 as my ZCD with "**C2530_CC2591_Default_20190608 firmware**" in it. Now I have 2 ZCD with same firmware.

In 1st ZCD I have added 10 lighting devices.
    2nd ZCD I have added 15 lighting devices.

Both sets of ZCD working fine individually and it can also be controlled, But when I am powering both ZCD at same time (or) placing the 1st ZCD closer to 2nd ZCD, then I can't control the lighting devices.

If I am turning off the any one ZCD, then I can control the another set of devices.

Is there any solution for this type of issue..?

**Comment by tabnul** [comment]
I think this is a general issue with zigbee routers / transmitters.

For instance when i place 2 ikea sockers next to each other (few cm in between) it is just a matter of time before one or the other will drop off the network. I think there are guidelines for placement in the zigbee documentation that confirm this.
