### ISSUE TITLE
Led(s) on Z-Stack_3.x.0

### ISSUE THREAD

**Issue by Gio-dot** [Koenkk/Z-Stack-firmware#256]
Hi, i noticed that in 3.x.0 firmware table (https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.x.0/bin) are reported leds on various boards. I'm working on a cc2652P module and noticed that leds on dio_7 and dio_8 are not working. Tried egony firmware: leds works as expected. I'm missing something or leds on this firmware are not yet implemented?

**Comment by Koenkk** [comment]
Indeed not supported for now, similar issue: https://github.com/Koenkk/Z-Stack-firmware/issues/203

**Comment by Gio-dot** [comment]
> Indeed not supported for now, similar issue: #203

Do you think you will add LED support in the future?

**Comment by Koenkk** [comment]
Let's continue in https://github.com/Koenkk/Z-Stack-firmware/issues/203
