### ISSUE TITLE
How to update without loosing any config

### ISSUE THREAD

**Issue by ProfDrYoMan** [Koenkk/Z-Stack-firmware#259]
Hi,

I know, this is no support forum, but I did not know where to ask the question.

I want to update my coordinator 3.x.0 version to the lastet. What do I need to ensure to keep all config/links/...?

Thanks.

Any pointers to the proper forum would be nice.

**Comment by Koenkk** [comment]
If using Zigbee2MQTT; just reflash your coordinator and Zigbee2MQTT will automatically restore a backup (https://www.zigbee2mqtt.io/information/FAQ.html#doesnt-require-repairing). If using anything else please open an issue at their project page.

**Comment by ProfDrYoMan** [comment]
As info for my use case with HomeAssistant and any other user of zigphy: https://github.com/zigpy/zigpy-znp#nvram
