### ISSUE TITLE
Router Link Quality frequently dropping to 0

### ISSUE THREAD

**Issue by roygbiv856** [Koenkk/Z-Stack-firmware#26]
I've got 2 2531 routers and 1 coordinator in my set up. Main floor = 1 2531 coord, 1 2531 router, 1 sengled LED bulb router. Upstairs = 1 2531 router, 1 sengled LED bulb router. Hassio shows me the link quality of my 2 2531 routers. One of them, which is on the same floor and about 18 ft away through a wall, frequently drops to 0. Honestly, it is more often 0 than not. The router on the second floor drops to 0, but not as frequently. Is this normal?

**Comment by P-Verbrugge** [comment]
Same here. My network was stable. I am not sure why this happens. It ran just fine before. Now suddenly it keeps dropping. Only one of the two is... :-( Did not change any router firmware.
