### ISSUE TITLE
old firmware date cc2530 with 2591

### ISSUE THREAD

**Issue by frank3523** [Koenkk/Z-Stack-firmware#266]
Just installed a cc2530+2591 and flashed with the latest router firmware.
But when I look in the log the firmware date is from 2018.
"date_code":"2018-09-26","definition":{"description":"[CC2530 router](http://ptvo.info/cc2530-based-zigbee-coordinator-and-router-112/)","exposes":
Is this correct ??

**Comment by Koenkk** [comment]
Yes, see https://github.com/Koenkk/zigbee2mqtt/issues/6106#issuecomment-774430225
