### ISSUE TITLE
coordinator_backup json

### ISSUE THREAD

**Issue by Shaman2** [Koenkk/Z-Stack-firmware#272]
Hi. I often ready when zigbee2mqtt is stopped, file coordinator_backup.json is created in data folder. I use cc2531 with 1.2 firmware. And I dont see file coordinator_backup.json in folder with zigbee2mqtt data. I see only:

.configuration.yaml.bk
configuration.yaml
database.db
database.db.backup
devices.yaml
groups.yaml
state.json

Why I dont see coordinator_backup.json ?

**Comment by Koenkk** [comment]
This is expected, for 1.2 we don't support backups since it's not necessary to recover a network.
