### ISSUE TITLE
Slaesh's CC2652RB only works with serialport <= 9.0.6

### ISSUE THREAD

**Issue by station7** [Koenkk/Z-Stack-firmware#274]
As detected in this [issue #6517 at zigbee2mqtt](https://github.com/Koenkk/zigbee2mqtt/issues/6517), Slaesh's CC2652RB stick does not work with [serialport 9.0.7](https://github.com/Koenkk/zigbee2mqtt/issues/6517#issuecomment-788917672). Can this be fixed with a firmware update? Otherwise the dependency of serialport needs to be frozen at 9.0.6...

**Comment by Koenkk** [comment]
I think the issue is in serialport, not the firmware itself. I will check when new updates of serialport appear.
