### ISSUE TITLE
CC2530 + CC2591 Zigbee 3.0 Firmware

### ISSUE THREAD

**Issue by samsam-rolon** [Koenkk/Z-Stack-firmware#275]
Hello
Regarding your documentation, I have build 2 CC2530 + CC2591 router to extend my Zigbee Networks ( I leave in a building a need to extend my network from my home to my garage). 
It works very well. Do you plain to update it in 3.0 ? Those devices with gain antenna extend very well across concrete wall the Zigbee range !

**Comment by Koenkk** [comment]
@ptvoinfo do you plan to do this?

**Comment by ptvoinfo** [comment]
@Koenkk, @samsam-rolon I don't see any reasons to build v3 firmware if v1.2 works well in all networks.
