### ISSUE TITLE
Z-Stack coordinator firmwares table

### ISSUE THREAD

**Issue by Gio-dot** [Koenkk/Z-Stack-firmware#276]
I have some doubt about [this table](https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator):
there are differences between maximum devices number capabilities between cc2538 and cc2652.

In [this thread](https://e2e.ti.com/support/wireless-connectivity/zigbee-and-thread/f/zigbee-thread-forum/809468/cc2652rb-what-is-main-difference-between-cc2652rb-cc2592-active-cc2538) however, they say that cc2652 have more capabilities over the cc2538:  which is the thruth?

**Comment by Koenkk** [comment]
Both are the truth. The firmware has been optimised a bit different. Potentially CC2652 devices can also be extended to this size.

CC2652/CC1352 has a more powerful CPU + the Texas Instruments stack is still maintained.
