### ISSUE TITLE
CC2531 source routing firmware binary is missing padding 0xff

### ISSUE THREAD

**Issue by osresearch** [Koenkk/Z-Stack-firmware#278]
The binary file in https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_Home_1.2/bin/source_routing/CC2531_SOURCE_ROUTING_20201128.zip doesn't have padding applied (only 0x3a800 bytes instead of 0x40000), which prevents the stick from booting after flashing.

**Comment by spinpwr** [comment]
I think the reason for that is the binary in the zip is intended for SerialBootTool from TI, and for that you don't need the padding.
See more in [#320](https://github.com/Koenkk/zigbee2mqtt/issues/320)

If you want to flash is directly (by CCdebugger or alternate method) you will need to objcopy the hex file to bin as described [here](https://www.zigbee2mqtt.io/information/alternative_flashing_methods.html#prepare-the-firmware).
Like this:
```
objcopy --gap-fill 0xFF --pad-to 0x040000 -I ihex CC2531ZNP-Prod.hex -O binary CC2531ZNP-Prod.bin
```
