### ISSUE TITLE
How to force direct pairing with CC2531?

### ISSUE THREAD

**Issue by osresearch** [Koenkk/Z-Stack-firmware#279]
The documentation mentions that only five direct paired routers are supported with the source routing firmware on the CC2531, but it is not clear how to ensure which devices are direct paired.  Is it the first to pair? Is there a way to relocate devices to rebalance the network?

**Comment by Koenkk** [comment]
Depending on your gateway you can open up joining only on a specific device. E.g. z2m: https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgerequestpermit_join
