### ISSUE TITLE
Which led in cotrollable on cc1352p?

### ISSUE THREAD

**Issue by th0m4sek** [Koenkk/Z-Stack-firmware#303]
Hi just quick question about 1.21.0 and Z-Stack 3.x.0 20210708
I'm using cc1352p (E79-400DM2005S module)
Which LED should be now controllable I've got dio_7 connected and it is lead as before update.(disable led option is active)

**Comment by Koenkk** [comment]
If you set disable led the led is always off, else the led will be on when joining is permitted.

**Comment by th0m4sek** [comment]
OK everything is working as it should my led was soldered wrong...
