### ISSUE TITLE
SONOFF ZigBEE 3.0 USB Dongle Plus Router Firmware

### ISSUE THREAD

**Issue by xxsirosxx** [Koenkk/Z-Stack-firmware#316]
Hello everyone.
I tried to flip the router firmware on the SONOFF ZigBEE 3.0 USB dongle Plus which I didn't succeed.
Whenever I plug in the dongle, I press the Boot button on the dongle.
The process is always canceled with the error.

>Initiate access to target: COM8 using 2-pin cJTAG.
>No response from device. Device may not be in bootloader mode. Reset device and try again.
If problem persists, check connection and baud rate.
>Connecting over serial bootloader failed: No response from device. Device may not be in bootloader mode. Reset device and try again.
If problem persists, check connection and baud rate.
>Failed to create device object.

![Unbenannt](https://user-images.githubusercontent.com/55346205/138606122-cfa294b0-93c6-4273-a9ba-bee5a8ae8060.jpg)

Maybe one of you can help me.

**Comment by Hedda** [comment]
> I wish we had firmware with hardware flow control active.

@tteck Probably best if post a new issue to request hardware flow control https://github.com/Koenkk/Z-Stack-firmware/issues

FYI, posted a separate request for a firmware with hardware flow control actived -> https://github.com/Koenkk/Z-Stack-firmware/issues/324 (if @tteck and others are interested).

**Comment by mkaatman** [comment]
> I've tried the script again. [https://github.com/JelmerT/cc2538-bsl](url) The stick does not respond to the same problem.
> 
> `C:\Users\Privat\cc2538-bsl-master\cc2538-bsl-master>py ./cc2538-bsl.py -p "com8" -evw "CC1352P2_CC2652P_launchpad_coordinator_20210708.hex" Opening port com8, baud 500000 Reading data from CC1352P2_CC2652P_launchpad_coordinator_20210708.hex Your firmware looks like an Intel Hex file Connecting to target... ERROR: Timeout waiting for ACK/NACK after 'Synch (0x55 0x55)'`

I was getting this exact error from within a docker container, but when I did it from the (linux) host it worked.

**Comment by Hedda** [comment]
> I was getting this exact error from within a docker container, but when I did it from the (linux) host it worked.

If use Docker then need to forward/map your device from host machine to Docker instance, preferably via docker-compose:

https://www.zigbee2mqtt.io/guide/installation/02_docker.html#creating-the-initial-configuration

https://www.zigbee2mqtt.io/guide/installation/02_docker.html#docker-compose

Also see example:

https://www.home-assistant.io/integrations/zha/#cant-connect-to-usb-device-and-using-docker

**Comment by mkaatman** [comment]
Yeah I have it mapped. I can access it from HA->zha and zygpy-znp but that firmware update failed every time and after I updated firmware I still can't find any other devices. Thanks for the link I'll double check my syntax to pass it through.

**Comment by Hedda** [comment]
> Yeah I have it mapped. **I can access it from HA->zha and zygpy-znp** but that firmware update failed every time

Then also make sure that you stop HA/ZHA app before upgrading as serial devices can only have one connection established.

**Comment by mkaatman** [comment]
Even with zha deleted I was getting it. I ultimately gave up and went back to conbee2 and everything if stable.

**Comment by zuzuman** [comment]
same here

**Comment by zuzuman** [comment]
It's still not working. Seems like flashing firmware locked bootloader completely, and device not working at all (super small power consumption). 
Auto-BSL just showing the timeout error `Timeout waiting for ACK/NACK after 'Synch (0x55 0x55)'`
Do you know, where I (we) can buy jtag module for re-flashing this?

**Comment by Hedda** [comment]
> Do you know, where I (we) can buy jtag module for re-flashing this?

https://electrolama.com/radio-docs/advanced/flash-jtag/

"The cheapest option for an officially supported debugger is the CC-DEVPACK-DEBUG, available from most common electronics distributors"

https://www.ti.com/tool/CC-DEVPACK-DEBUG

Guess should be able to use most debuggers compatible with cJTAG (IEEE 1149.7 "Compact JTAG") via exposed TMS and TCK

**Comment by Hedda** [comment]
> FYI, several Home Assistant community members have tested Sonoff provided uartLog.py script which seems to confirm "Auto BSL" is working(?), so maybe possible to enter bootloader without need to open enclosure to manually press BTL button:
> 
> https://community.home-assistant.io/t/itead-sonoff-zigbee-3-0-usb-dongle-plus-adapter-based-on-texas-instruments-cc2652p/340705/45
> 
> https://community.home-assistant.io/t/itead-sonoff-zigbee-3-0-usb-dongle-plus-adapter-based-on-texas-instruments-cc2652p/340705/96
> 
> See uartlog.zig attached inside this docx which if unpacked contains uartLog.py
> 
> https://sonoff.tech/wp-content/uploads/2021/09/Zigbee-3.0-USB-dongle-plus-firmware-flashing-1-1.docx
> 
> cc2538-bsl.py also supports "Auto-BSL"
> 
> https://github.com/JelmerT/cc2538-bsl
> 
> See more information on what "Auto-BSL" does here:
> 
> https://electrolama.com/radio-docs/bsl/#auto-bsl
> 
> If can get that to work then can skip the BSL pushbutton press step to get the device into BSL mode in order for flashing it.


I have confirmed that running this script does indeed make ITead's Sonoff Zigbee 3.0 Plus adapter enter bootloader mode and after that I could flash it directly with  `llama-bsl.py -p COM5 -b 115200 -evw CC1352P2_CC2652P_launchpad_coordinator_20210708.hex` without having open its enclosure and pressing the BRL button which I think is very convenient. The script also lists all active COM ports on MS Windows (tested on Windows 10) and have you enter the number of the COM port, but note that the script is hardcoded for Windows COM ports.

**Comment by zuzuman** [comment]
Is it possible to flash without c/jTag? With Raspberry only?

**Comment by Hedda** [comment]
> Is it possible to flash without c/jTag? With Raspberry only?

Maybe check out this -> https://gist.github.com/hwhw/fc43892785aa84913d03495c97b0f25a 

That is written for CC2538 but could be maybe be similar if it works without TDI and TDO. As what I needed is a cJTAG programming mode because CC2652 uses that by default. cJTAG mode only uses RESET, TCK and TMS pins, as CC2652 doesn't have TDI and TDO. You of course also need POWER (VCC) and GROUND.

![image](https://user-images.githubusercontent.com/6320001/141115525-3993448b-f16a-4df4-8e66-db438b0da214.png)

**Comment by zuzuman** [comment]
After router firmware update device is dead. 
R.I.P. my sonoff device :(

**Comment by Hedda** [comment]
> After router firmware update device is dead. R.I.P. my sonoff device :(

Even if can no longer get into the bootloader you should still be able to unbrick the hardware if flash using cJTAG via TCK and TMS.

https://electrolama.com/radio-docs/advanced/flash-jtag/

https://www.ti.com/tool/CC-DEVPACK-DEBUG

**Comment by VoyteckPL** [comment]
I have the same problem. What is the reset button for? How can I revert to coordinator software?

**Comment by Hedda** [comment]
> How can I revert to coordinator software?

To revert you just need to flash a coordinator firmware again:

https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.x.0/bin

https://github.com/Koenkk/Z-Stack-firmware/tree/develop/coordinator/Z-Stack_3.x.0/bin

To flash suggest you test this -> https://github.com/JelmerT/cc2538-bsl/pull/114 and report flashing success or not there.

**Comment by VoyteckPL** [comment]
> > How can I revert to coordinator software?
> 
> To revert you just need to flash a coordinator firmware again (CC1352P2_CC2652P_launchpad_*.zip):
> 
> https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.x.0/bin
> 
> https://github.com/Koenkk/Z-Stack-firmware/tree/develop/coordinator/Z-Stack_3.x.0/bin
> 
> To flash suggest you test this -> [JelmerT/cc2538-bsl#114](https://github.com/JelmerT/cc2538-bsl/pull/114) (and report flashing success or not there).

The problem is the it doesn't go into bootloader mode.... I hold boot button when plugging it in.

**Comment by Hedda** [comment]
> The problem is the it doesn't go into bootloader mode.... I hold boot button when plugging it in.

With this patch you should not need to press any buttons at all as it will enter BSL via software -> https://github.com/JelmerT/cc2538-bsl/pull/114

**Comment by npirtube** [comment]
Hi xxsirosxx would you mind sharing a download link for the SmartRF Flash Programmer tool?

From the TI website it is impossible to download it and I can't find it anywhere to download.

**Comment by xxsirosxx** [comment]
> Hallo xxsirosxx, würde es Ihnen etwas ausmachen, einen Download-Link für das SmartRF Flash Programmer-Tool zu teilen?
> 
> Von der TI-Website ist es unmöglich, es herunterzuladen, und ich kann es nirgendwo zum Herunterladen finden.

Hi I would rather recommend ZigStar. https://github.com/xyzroe/ZigStarGW-MT

**Comment by xxsirosxx** [comment]
Hi I would rather recommend ZigStar. https://github.com/xyzroe/ZigStarGW-MT

**Comment by Hedda** [comment]
> Hi I would rather recommend ZigStar. https://github.com/xyzroe/ZigStarGW-MT

FYI, ZigStar GW Multi tool doesn't yet support flashing USB adapters using Silabs CP2102N like ITead's Sonoff USB Plus Dongle, see:

https://github.com/xyzroe/ZigStarGW-MT/issues/2

**Comment by davrodfer** [comment]
> Is it possible to flash without c/jTag? With Raspberry only?

These are my steps in an raspberry-pi:

```
export BASEDIR=`~/sonoff_dongle/`
mkdir -p $BASEDIR
cd $BASEDIR
git clone https://github.com/JelmerT/cc2538-bsl.git
git clone https://github.com/Koenkk/Z-Stack-firmware.git
unzip Z-Stack-firmware/coordinator/Z-Stack_3.x.0/bin/CC1352P2_CC2652P_launchpad_*.zip
sudo service zigbee2mqtt stop
pip3 install pyserial intelhex python-magic
```
+ Remove bolts and extract usb from metallic enclosure
+ Press and hols button BOOT
+ Insert usb in usb port holding BOOT
+ Releade BOOT after 3 seconds
```
python3 $BASEDIR/cc2538-bsl/cc2538-bsl.py -p /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus* -evw  $BASEDIR/CC1352P2_CC2652P_launchpad_coordinator_*.hex
```

**Comment by Hedda** [comment]
@davrodfer But that will not work if you first accidentally flashed it with the wrong firmware image and messed up the bootloader.

So if you "bricked it" then you will need to "unbrick it" by flashing it via a c/JTAG debug probe instead of flashing it via USB.

That is, if you do not have a working bootloader then think it will need to support 2-pin cJTAG (a.k.a C-JTAG or c/JTAG) and not just common JTAG SWD as TI CC2652 debug do not use SWD and SWDCLK, etc. but instead only TMS and TCK (cJTAG is not SWD/SWDCLK). See details at → [Flash Firmware using c/JTAG - Electrolama](https://electrolama.com/radio-docs/advanced/flash-jtag/)

Looking at pictures on _[ITead’s product page for the Sonoff CC2552P board](https://itead.cc/product/sonoff-zigbee-3-0-usb-dongle-plus/)_ you see that no SWD and SWDCLK pads are exposed, but it does expose TMS and TCK pads so those is what you need to use.

So will probably need cJTAG debug probe with TMS and TCK, and thus you will need to use a cJTAG compatible debugger probe adapter like Texas Instruments XDS110 or a clone of TI’s XDS110.

![image](https://user-images.githubusercontent.com/6320001/150363570-41532adb-15fb-4d4c-b2a6-1d9144227c1d.png)

Again, the official Texas Instruments TMDSEMU110-U XDS110 JTAG Debug Probe is a bit expensive and currently looks to be out-of-stock, but cheap clones of XDS110 JTAG debug probe should work, see example:

https://aliexpress.com/item/4000751867419.html

https://www.ti.com/tool/TMDSEMU110-U

**Comment by andreytse** [comment]
Sorry for off topic and stupid question, but if I will flash dongle with router firmware, did it start working like zigbee network extender? No need to be connected directly to "computer"? Just simple 5VDC power supply  like phone charger will be enough?

**Comment by ptvoinfo** [comment]
@andreytse Yes, it works as an extender. You need 5V only.

**Comment by io53** [comment]
> @davrodfer But will that work if first have accidentally flashed it with the wrong firmware image and messed up the bootloader?
> 
> > Maybe check out this: https://gist.github.com/hwhw/fc43892785aa84913d03495c97b0f25a
> > That is written for CC2538 but could be maybe be similar if it works without TDI and TDO. As what you needed is a cJTAG programming mode because CC2652 uses that by default. cJTAG mode only uses RESET, TCK and TMS pins, as CC2652 doesn't have TDI and TDO. You of course also need POWER (VCC) and GROUND.
> 
> So if you "bricked it" then you will need to "unbrick it" by flashing firmware via a c/JTAG debug probe instead of flashing it via USB.
> 
> That is, if you do not have a working bootloader then think it will need to flash via the 2-pin cJTAG (a.k.a C-JTAG or c/JTAG) and not just common JTAG SWD as TI CC2652 debug do not use SWD and SWDCLK, etc. but instead only TMS and TCK (cJTAG is not SWD/SWDCLK). See details at → [Flash Firmware using c/JTAG - Electrolama](https://electrolama.com/radio-docs/advanced/flash-jtag/)
> 
> https://electrolama.com/radio-docs/advanced/flash-jtag/
> 
> Looking at pictures on _[ITead’s product page for the Sonoff CC2552P board](https://itead.cc/product/sonoff-zigbee-3-0-usb-dongle-plus/)_ you see that no SWD and SWDCLK pads are exposed, but it does expose TMS and TCK pads so those is what you need to use.
> 
> So will probably need cJTAG debug probe (e.i. external debugger adapter) with TMS and TCK, and thus you will need to use a cJTAG compatible debugger probe adapter like Texas Instruments XDS110 or a clone of TI’s XDS110.
> 
> ![image](https://user-images.githubusercontent.com/6320001/150363570-41532adb-15fb-4d4c-b2a6-1d9144227c1d.png)
> 
> Again, the official Texas Instruments TMDSEMU110-U XDS110 JTAG Debug Probe is a bit expensive and currently looks to be out-of-stock, but cheap clones of XDS110 JTAG debug probe should work, see example:
> 
> https://aliexpress.com/item/4000751867419.html
> 
> https://www.ti.com/tool/TMDSEMU110-U

As the TI Launchpad devkits has onboard XDS110, I guess those can be used for flashing also. Way cheaper than an official standalone debugger and as a bonus you can use it as coordinator/router too :).

**Comment by Hedda** [comment]
> As the TI Launchpad devkits has onboard XDS110, I guess those can be used for flashing also. Way cheaper than an official standalone XDS110 and as a bonus you can use it as coordinator/router too :).

Yes the TI LAUNCHXL-CC26xR1 and the TI LAUNCHXL-CC1352P does have integrated XDS110 debugger, but the cheapest standa-alone option today for an officially supported debugger adapter is the Texas Instruments CC-DEVPACK-DEBUG:

https://www.ti.com/tool/CC-DEVPACK-DEBUG

However, the official TMDSEMU110-U XDS110 JTAG Debug Probe is still a better option for developers as offer more options:

https://www.ti.com/tool/TMDSEMU110-U

The original Texas Instruments XDS110 JTAG debug probe is a bit expensive but cheap clones of it should also work, examples:

https://aliexpress.com/item/4000751867419.html

https://aliexpress.com/item/32976279419.html

Also, note that original Segger J-Link V9 (legacy) debug probes does not support cJTAG, so need at least Segger J-Link V10 series:

https://wiki.segger.com/J-Link_Model_Overview

**Comment by shudack** [comment]
In the path you need to remove the spaces. I noticed that you have spaces in path: "...ee Stick/CC1352P2..."
Try to put the hex file in C:\

E.g.: C:\CC1352P2_CC2652P_launchpad_coordinator_20211217.hex

**Comment by heapxor** [comment]
Hello,
i tried to flash firmware using official docx and app Flashprogrammer crashed during the process... 
So i opened device, pressed button to get booaloader etc... and reflashed

>Initiate access to target: COM5 using 2-pin cJTAG.
>Reading file: C:/Users/xxx/Downloads/cc2538-bsl-master/CC1352P2_CC2652P_launchpad_router_20220125.hex.
>Start flash erase ...
>Erase finished successfully.
>Start flash programming ...
>Programming finished successfully.
>Start flash verify ...
>Skip verification of unassigned page: 23.
>Skip verification of unassigned page: 24.
>Skip verification of unassigned page: 25.
>Skip verification of unassigned page: 26.
>Skip verification of unassigned page: 27.
>Skip verification of unassigned page: 28.
>Skip verification of unassigned page: 29.
>Skip verification of unassigned page: 30.
>Skip verification of unassigned page: 31.
>Skip verification of unassigned page: 32.
>Skip verification of unassigned page: 33.
>Skip verification of unassigned page: 34.
>Skip verification of unassigned page: 35.
>Skip verification of unassigned page: 36.
>Skip verification of unassigned page: 37.
>Skip verification of unassigned page: 38.
>Skip verification of unassigned page: 39.
>Skip verification of unassigned page: 40.
>Skip verification of unassigned page: 41.
>Skip verification of unassigned page: 42.
>Page: 0 verified OK.
>Page: 1 verified OK.
>Page: 2 verified OK.
>Page: 3 verified OK.
>Page: 4 verified OK.
>Page: 5 verified OK.
>Page: 6 verified OK.
>Page: 7 verified OK.
>Page: 8 verified OK.
>Page: 9 verified OK.
>Page: 10 verified OK.
>Page: 11 verified OK.
>Page: 12 verified OK.
>Page: 13 verified OK.
>Page: 14 verified OK.
>Page: 15 verified OK.
>Page: 16 verified OK.
>Page: 17 verified OK.
>Page: 18 verified OK.
>Page: 19 verified OK.
>Page: 20 verified OK.
>Page: 21 verified OK.
>Page: 22 verified OK.
>Page: 43 verified OK.
>Verification finished successfully.
>Reset target ...
>Reset of target successful.


Even reflashed it doesnt work at all... is it possible that Crash - bricked it?
In case it was bricked is it possible to unbrick?

thanks!

**Comment by hvanmegen** [comment]
I have the exact same problem; ordered a 2-pack of these dongles to replace by broken old zigbee stick based on the older (unstable) chips.. but I can't get them to start in bootloader/flashing-prepared mode either, no matter how long I keep the button pressed after inserting the device into an USB slot. I'm going to try and see if the https://github.com/JelmerT/cc2538-bsl/pull/114 thing works, otherwise I just spent 32 euro's on 2 underweight paperweights..

**Comment by hvanmegen** [comment]
I got it to work after I installed the CP210x Universal driver @ https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers.

Then when I ran this command in Windows Powershell (after installing Python and running `pip install pyserial intelhex`):

`$comports = Get-WMIObject Win32_SerialPort; $comports |Get-PnpDeviceProperty -InstanceId {$_.pnpdeviceid} -Keyname DEVPKEY_Device_BusReportedDeviceDesc |ForEach-Object { foreach($comport in $comports) {if ($comport.pnpdeviceid -eq $_.instanceid) { new-object psobject -property @{COMPORT = $comport.deviceid; 'Device-Name' = $_.data} } } }`

It then showed the device plugged into the COM3 port:
```
> $comports = Get-WMIObject Win32_SerialPort; $comports |Get-PnpDeviceProperty -InstanceId {$_.pnpdeviceid} -Keyname DEVPKEY_Device_BusReportedDeviceDesc |ForEach-Object { foreach($comport in $comports) {if ($comport.pnpdeviceid -eq $_.instanceid) { new-object psobject -property @{COMPORT = $comport.deviceid; 'Device-Name' = $_.data} } } }

COMPORT Device-Name
------- -----------
COM3    Sonoff Zigbee 3.0 USB Dongle Plus
```
After that I could run the command to flash the device into coordinator mode by running `python cc2538-bsl.py -p COM3 -evw --bootloader-sonoff-usb .\coordinator.hex`.

**Comment by Tstrijker** [comment]
> I got it to work after I installed the CP210x Universal driver @ https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers.
> 
> Then when I ran this command in Windows Powershell (after installing Python and running `pip install pyserial intelhex`):
> 
> `$comports = Get-WMIObject Win32_SerialPort; $comports |Get-PnpDeviceProperty -InstanceId {$_.pnpdeviceid} -Keyname DEVPKEY_Device_BusReportedDeviceDesc |ForEach-Object { foreach($comport in $comports) {if ($comport.pnpdeviceid -eq $_.instanceid) { new-object psobject -property @{COMPORT = $comport.deviceid; 'Device-Name' = $_.data} } } }`
> 
> It then showed the device plugged into the COM3 port:
> 
> ```
> > $comports = Get-WMIObject Win32_SerialPort; $comports |Get-PnpDeviceProperty -InstanceId {$_.pnpdeviceid} -Keyname DEVPKEY_Device_BusReportedDeviceDesc |ForEach-Object { foreach($comport in $comports) {if ($comport.pnpdeviceid -eq $_.instanceid) { new-object psobject -property @{COMPORT = $comport.deviceid; 'Device-Name' = $_.data} } } }
> 
> COMPORT Device-Name
> ------- -----------
> COM3    Sonoff Zigbee 3.0 USB Dongle Plus
> ```
> 
> After that I could run the command to flash the device into coordinator mode by running `python cc2538-bsl.py -p COM3 -evw --bootloader-sonoff-usb .\coordinator.hex`. (after copying the coordinator firmware to coordinator.hex in the directory of the perl script, obviously)

The CP210x Universal driver solved the problem for me. If your on Windows check if the driver are correly installed for the com port. Thank you @hvanmegen for you solution.

**Comment by janmashat** [comment]
Have any Windows users tried this docker path?
https://github.com/JelmerT/cc2538-bsl/issues/120

**Comment by kanapka94** [comment]
> I got it to work after I installed the CP210x Universal driver @ https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers.
> 
> Then when I ran this command in Windows Powershell (after installing Python and running `pip install pyserial intelhex`):
> 
> `$comports = Get-WMIObject Win32_SerialPort; $comports |Get-PnpDeviceProperty -InstanceId {$_.pnpdeviceid} -Keyname DEVPKEY_Device_BusReportedDeviceDesc |ForEach-Object { foreach($comport in $comports) {if ($comport.pnpdeviceid -eq $_.instanceid) { new-object psobject -property @{COMPORT = $comport.deviceid; 'Device-Name' = $_.data} } } }`
> 
> It then showed the device plugged into the COM3 port:
> 
> ```
> > $comports = Get-WMIObject Win32_SerialPort; $comports |Get-PnpDeviceProperty -InstanceId {$_.pnpdeviceid} -Keyname DEVPKEY_Device_BusReportedDeviceDesc |ForEach-Object { foreach($comport in $comports) {if ($comport.pnpdeviceid -eq $_.instanceid) { new-object psobject -property @{COMPORT = $comport.deviceid; 'Device-Name' = $_.data} } } }
> 
> COMPORT Device-Name
> ------- -----------
> COM3    Sonoff Zigbee 3.0 USB Dongle Plus
> ```
> 
> After that I could run the command to flash the device into coordinator mode by running `python cc2538-bsl.py -p COM3 -evw --bootloader-sonoff-usb .\coordinator.hex`. (after copying the coordinator firmware to coordinator.hex in the directory of the python script, obviously)

It works ! Also after installa Universal Drivers Sonof Dongle appeared in Flash Programmer 2

**Comment by hvanmegen** [comment]
Very glad to see that me posting my solution here helped at least 2 other people.. We are The Community, my friends.. stay awesome!

**Comment by david-steg** [comment]
I still have "ERROR: Timeout waiting for ACK/NACK after 'Synch (0x55 0x55)" :(.

**Comment by Hedda** [comment]
> I still have "ERROR: Timeout waiting for ACK/NACK after 'Synch (0x55 0x55)" :(.

Manually enable bootloader mode via boot button or use correct parameters for Sonoff with https://github.com/JelmerT/cc2538-bsl

**Comment by moment74haos** [comment]
ніяк неможу найти прошивку CC1352P2_CC2652P_launchpad_coordinator_20210708.hex можливо в когось є? підкажіть будьласка

**Comment by janmashat** [comment]
https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.x.0/bin

**Comment by moment74haos** [comment]
тут є нова версія прошивки 2024 року CC1352P2_CC2652P_launchpad_coordinator_20240710.zip а я шукаю старішу  2021 року CC1352P2_CC2652P_launchpad_coordinator_20210708
