### ISSUE TITLE
Latest CC2652RB firmware breaks pairing (Interview proces) the LIDL HG06335 motion sensor

### ISSUE THREAD

**Issue by adekloet** [Koenkk/Z-Stack-firmware#317]
For those who are looking for the reason why the LIDL HG06335 does not pair (well it does pair, but does not report on values because of a failed interview process) anymore with the new firmware, the new firmware CC2652RB fixed one issue and introduced a new one in which this particular senor does not report on value's after pairing (failed interview proces). 

Confirmed working again with a test setup using another coordinator (Conebee II).

If the initial bug which was fixed with the latest firmware does not bother you, you could also downgrade the CC2652RB firmware to get it up and running again. Running HG06335 sensors have been interviewed under the old firmware continue to work! Do not try to re-pair them on the new firmware!

Referring to topic: 

https://github.com/Koenkk/zigbee2mqtt/discussions/9273

Hope this help others looking for the same issue's
Cheers
Alex

**Comment by Delta1977** [comment]
Looks like there is a new SDK?  : 
SIMPLELINK-CC13XX-CC26XX-SDK
SimpleLink™ CC13xx and CC26xx software development kit (SDK)
Version: 5.30.01.01
Release date: 23 Nov 2021

https://www.ti.com/tool/SIMPLELINK-CC13XX-CC26XX-SDK

**Comment by Koenkk** [comment]
@Delta1977 update can be found here: https://github.com/Koenkk/Z-Stack-firmware/tree/develop/coordinator/Z-Stack_3.x.0/bin
