### ISSUE TITLE
2652 firmware does not support ZGP (Zigee Green Power)

### ISSUE THREAD

**Issue by khaidakin** [Koenkk/Z-Stack-firmware#318]
I recently bought tuya K9Z-TY switches that work on the ZGP protocol. They work fine with the tuya gateway. On the 2538 stick, the connection process starts, but then the 2538 stick hangs tight, until the stick is physically rebooted. Here is the connection log https://pastebin.com/HNqNRKcF On the EFR32 stick, the connection process goes through, but the device does not appear in the list of connected devices, although the commands from the buttons are visible in the debugger. And on the 2652 stick in the debugger, I don't see any messages at all.
How can I connect ZGP devices to Z2M?

**Comment by Hedda** [comment]
Can not find "K9Z-TY", "K9ZTY", "TY-K9Z", or "TYK9Z" listed on the Zigbee2MQTT website for supported devices:

https://www.zigbee2mqtt.io/supported-devices/

So support probably need to be added to zigbee-herdsman-converters first (and maybe zigbee-herdsman too):

https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

https://github.com/Koenkk/zigbee-herdsman-converters

https://github.com/Koenkk/zigbee-herdsman/

**Comment by khaidakin** [comment]
> Can not find "K9Z-TY", "K9ZTY", "TY-K9Z", or "TYK9Z" listed on the Zigbee2MQTT website for supported devices:
> 
> https://www.zigbee2mqtt.io/supported-devices/
> 
> So support probably need to be added to zigbee-herdsman-converters first by adding a converter for it:

I already wrote that now the problem is not with the converters for ZGP, but that the firmware for devices based on cc2652 does not work with these devices. From the word at all.

**Comment by fmarkf** [comment]
SMARTLIGHT CC2652P Zigbee USB dongle V4.
Flashed with Z-Stack 3.x.0 20210708 firmware.

Unfortunately I'm also having the same problem trying to pair Philips Hue Tap switch:
https://www.zigbee2mqtt.io/devices/8718696743133.html

Nothing appears in the log.

Any help would be appreciated.
Thanks!

**Comment by fmarkf** [comment]
Not sure how ZGP things in the firmware work, but I was able to pair Philips Hue Tap switch via Ikea repeater.
As a side note - my network consists of a battery-powerd sensors only (plus Ikea repeater now).

I guess this is not a real solution, but at least it allows Hue Tap to be added to the network.

**Comment by Danit2** [comment]
Do you have read this?
https://www.zigbee2mqtt.io/devices/8718696743133.html#green-power

I have one ZGP Device in my network and this is working fine.
But i have a hue device in the range of the Tab.

**Comment by fmarkf** [comment]
> Do you have read this? https://www.zigbee2mqtt.io/devices/8718696743133.html#green-power
> 
> I have one ZGP Device in my network and this is working fine. But i have a hue device in the range of the Tab.

Yes, I read it. 
However the thing is -it worked fine without any repeater with  Deconz Conbee 2 USB stick. So I assumed it should work with SMARTLIGHT CC2652P as well.

My guess is - if it works with Deconz, it should work with other ZigBee coordinators.

My only reason to switch to SMARTLIGHT CC2652P was to get better signal strength and range.

**Comment by Danit2** [comment]
I have also a SMARTLIGHT CC2652P stick and when the HUE device is not online the Tap dosen't work.
The same was with the Slaesh's CC2652RB stick that i have befor. 

When Deconz support ZGP then they must also be possible with the other adapters. 
But then the firmware of the adapters must support that. 
Maby this will come later.

**Comment by khaidakin** [comment]
Friends, I opened this issue to draw the attention of the author of the firmware for coordinators based on 2652, that it does not support working with ZGP devices. I hope that your comments will be heard and support for ZGP devices will be added to the 2652 firmware

**Comment by khaidakin** [comment]
Is there really no way to add support for ZGP devices to the firmware for 2652 coordinators? Isn't that interesting to anyone else?

**Comment by dim6003** [comment]
There is going to be more and more devices, not only Philips, using ZGB in the near future, So I'm in line with OP that's going to be a needed feature. Having a Hue device in range is not a perennial solution!

**Comment by s-hadinger** [comment]
Is it possible to reopen this issue? I successfully got traffic from ZGP switches as long as there is a GPP (proxy) in the network. But when the CC2652P is alone, it doesn't seem to do anything with ZGP frames. I tried to send to itself GP Commissioning commands but no success.

**Comment by s-hadinger** [comment]
It appears that the GP Proxy code is not enabled in coordinator ZNP code, even in the most recent versions. It is only in the sink examples, but it won't help us here.

I have compiled a new version of ZStack for CC2652P trying to enable just the basic reception of GP frames. I will try tomorrow if it's enough to just get the frames received.

**Comment by Hedda** [comment]
@Koenkk Should this issue maybe be reopened for tracking purposes?

**Comment by s-hadinger** [comment]
I tried several options : enable GP_DATA_IND callback (no effect), enable GP proxy and sink (no effect). I'm giving up

**Comment by Hedda** [comment]
@Koenkk is ZGP Proxy code now enabled in your latest Zigbee Coordinator ZNP config for Z-Stack 3.x.0 builds?
