### ISSUE TITLE
SONOFF Zigbee 3.0 USB Dongle Plus: Bluetooth activation possible?

### ISSUE THREAD

**Issue by end84** [Koenkk/Z-Stack-firmware#322]
Hey there,

according to the [TI CC2652P datasheet](https://www.ti.com/lit/ds/symlink/cc2652p.pdf) the CC2652P has Bluetooth 5.2. It's generally possible to activate this using a firmware update?

**Comment by Koenkk** [comment]
Should be possible, but I believe bluetooth and zigbee cannot be activated together. This repo focusses on Zigbee fws only.
