### ISSUE TITLE
git apply patch 

### ISSUE THREAD

**Issue by yaniv1111** [Koenkk/Z-Stack-firmware#33]
Hi,

Im trying to apply "fireware.patch" file and got this errors

MINGW64 /c/Texas Instruments/Z-Stack Home 1.2.2a.44539                             $ ls                                                                                           _iss/                                                                                         Accessories/                                                                                  Components/                                                                                   Documents/                                                                                    EULA.pdf                                                                                      firmware.patch                                                                               'Getting Started Guide - CC2530.pdf'                                                          'Getting Started Guide - CC2538.pdf'                                                           Projects/                                                                                     Tools/                                                                                       'Z-Stack Core Release Notes.txt'                                                              'Z-Stack Home Release Notes.txt'                                                              'Z-Stack Home Software Development Kit Resource Guide.html'                                    Z-Stack_Home_1.2.2_Manifest.pdf                                                                                                                                                            YK@WIN7-PC MINGW64 /c/Texas Instruments/Z-Stack Home 1.2.2a.44539                             $ git apply firmware.patch                                                                    firmware.patch:41: trailing whitespace.                                                       #define CODE_REVISION_NUMBER 20190109                                                         firmware.patch:73: trailing whitespace.                                                                                                                                                     firmware.patch:79: trailing whitespace.                                                                                                                                                     firmware.patch:89: trailing whitespace.                                                       // Shared accross all firmwares                                                               firmware.patch:90: trailing whitespace.                                                       #define ASSERT_RESET                                                                          error: patch failed: Projects/zstack/ZNP/Source/znp.cfg:101                                   error: Projects/zstack/ZNP/Source/znp.cfg: patch does not apply
--

thanks
Yaniv

**Comment by Koenkk** [comment]
Is this a clean Z-Stack install?

**Comment by yaniv1111** [comment]
yes on windows 10

**Comment by Koenkk** [comment]
Can you check if this has been fixed?

**Comment by yaniv1111** [comment]
yes. this has been fixed by:
dos4unix fireware.patch
and trimming all leading spaces using notepad++

**Comment by yaniv1111** [comment]
I'm tring to set FIRMWARE_CC2531_DEFAULT or FIRMWARE_CC2531_MAX_DEVICES but I dont see it in "defined symbols"

![image](https://user-images.githubusercontent.com/6318653/52372333-99f97400-2a60-11e9-99c0-9b11cf6727ae.png)

**Comment by Koenkk** [comment]
You need to remove all symbols and only add FIRMWARE_CC2531_DEFAULT

**Comment by yaniv1111** [comment]
I tried to rebuild but got this errors.

[output.built_all.txt](https://github.com/Koenkk/Z-Stack-firmware/files/2842252/output.built_all.txt)
