### ISSUE TITLE
Z-Stack_Home_1.2 (default) aqara issues

### ISSUE THREAD

**Issue by xsaren11** [Koenkk/Z-Stack-firmware#331]
Hello,

I would like to report some issues with my Aqara devices.
Yesterday I downloaded the newest software for Z-Stack_Home_1.2 (default) CC2531 but now I have more troubles then before

Here is an example.

Aqara button now do not posting action state
![image](https://user-images.githubusercontent.com/29581516/144231369-d3ab7cfb-651b-4765-8ddf-16e454776ac6.png)

Aqara door sensor is not supported (old version and new version)
![image](https://user-images.githubusercontent.com/29581516/144231541-f8a2657c-d91f-4e17-9312-f63b2dee0179.png)

Best Regards
Krzysztof

**Comment by pfischbach** [comment]
After installing this release I can not pair IKEA E1524 remote similar to the Aqara obove. Works with last version.
error 2021-12-01 16:46:31: Failed to interview '0x000b57fffeaf6075', device has not successfully been paired
info  2021-12-01 16:46:31: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x000b57fffeaf6075","ieee_address":"0x000b57fffeaf6075","status":"failed"},"type":"device_interview"}'
info  2021-12-01 16:46:31: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_failed","meta":{"friendly_name":"0x000b57fffeaf6075"},"type":"pairing"}'
info  2021-12-01 16:46:59: Zigbee: allowing new devices to join.

**Comment by xsaren11** [comment]
With new version of Zigbee2MQTT everything works fine

**Comment by phretor** [comment]
@xsaren11 edge or stable? And what firmware version?

**Comment by xsaren11** [comment]
This
one coordinator/Z-Stack_Home_1.2/bin/default/CC2531_DEFAULT_20211115.zip
from master branch
