### ISSUE TITLE
Led Off support for ZigStar LAN Coordinator

### ISSUE THREAD

**Issue by CSchoch** [Koenkk/Z-Stack-firmware#340]
Could you please support disabling leds for ZigStar LAN Coordinator?

If i disable it in Z2M it won't start up telling me adapter does not support led control

**Comment by Hedda** [comment]
Should that maybe also be reported to https://github.com/xyzroe/ZigStarGW-FW and https://github.com/xyzroe/ZigStarGW-FW ?

**Comment by xyzroe** [comment]
You just need to change Zigbee firmware to a version that supports control LEDs from z2m.  
For example the last one from Koenkk

**Comment by CSchoch** [comment]
Ok, thanks a lot.
