### ISSUE TITLE
[question] max devices with cc2531

### ISSUE THREAD

**Issue by yaniv1111** [Koenkk/Z-Stack-firmware#35]
can I flash the *.hex file in https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/CC2531/alternatives/max_devices/bin/CC2531ZNP-Prod_20181224.zip

same as I  flash it in https://www.zigbee2mqtt.io/getting_started/flashing_the_cc2531.html
?

thanks?

**Comment by Koenkk** [comment]
yes

**Comment by yaniv1111** [comment]
thx
