### ISSUE TITLE
CC2652P Ebyte E72-2G4M20S1E not working on HA OS 7.4

### ISSUE THREAD

**Issue by bruvv** [Koenkk/Z-Stack-firmware#352]
I updated my HA OS to 7.4 and out of the blue my zigbee stick with the latest firmware stopped being registered as ttyACM0. It is now ttyUSB0. Why did this change?
View the complete issue here: https://github.com/home-assistant/operating-system/issues/1748

**Comment by realthk** [comment]
Why do you use ttyACM* in the first place?
It is recommended to use device id instead: [https://www.zigbee2mqtt.io/guide/configuration/adapter-settings.html](https://www.zigbee2mqtt.io/guide/configuration/adapter-settings.html)

In HAOS, you can check ids even on the GUI: /hassio/system, Host, 3 dots menu, hardware.

I have 
```
serial:
  port: >-
    /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_22_98_8D_0E-if00-port0
```
for mine in the config of Zigbee2mqtt addon, and have no problem with 7.4 (on an HP T620, like you)
