### ISSUE TITLE
Zigbee battery reading is wrong

### ISSUE THREAD

**Issue by fg0003** [Koenkk/Z-Stack-firmware#358]
Hello,
after Zigbee adapter update today to 1.6.16 the battery symbol in the Zigbee settings for the
Xiaomi Aqara door & window contact sensors MCCGQ11LM are all showing red and the reading for all are below 50% although the voltage is showing approx. 3 volt. 
![zigbee](https://user-images.githubusercontent.com/73749854/155017934-66759a81-0c3c-43ad-ba89-4c87c855e9cf.jpg)

**Comment by Koenkk** [comment]
This is expected, see https://github.com/Koenkk/zigbee2mqtt/issues/8499
