### ISSUE TITLE
I can see there is already coordinator with 5.40 SDK in development branch, is there a plan for a router with 5.40? Thank you

### ISSUE THREAD

**Issue by wojciechczyz** [Koenkk/Z-Stack-firmware#360]
I can see there is already coordinator with 5.40 SDK in development branch, is there a plan for a router with 5.40? Thank you

_Originally posted by @wojciechczyz in https://github.com/Koenkk/Z-Stack-firmware/issues/341#issuecomment-1050839381_

**Comment by Koenkk** [comment]
May publish the later when the coordinator firmware is merged to master, so yes I plan to keep it up-to-date.
