### ISSUE TITLE
smlight-slzb-05 "Update Failed: Wrong Magic Byte"

### ISSUE THREAD

**Issue by blackie333** [Koenkk/Z-Stack-firmware#363]
Hello,
I'm trying to update Zigbee firmware in my "SMARTLIGHT Zigbee LAN Adapter CC2652P Model SLZB-05" to the latest version "CC1352P2_CC2652P_other_coordinator_20220219.hex" via adaptor web interface but every attempt ends with an error: "Update Failed: Wrong Magic Byte". 
Restart of the adaptor or Toggle to flashmode before flashing has no effect, still the same result.
Bought this model because of easy flashing via web, but my first attempt leads to problems.
Not sure what else to try, please advice me the correct procedure. Thnx

**Comment by giovbolo** [comment]
I have the same problem  when flashing  the Zigbee firmware version "CC1352P2_CC2652P_other_router_20220125.hex" in my "SMARTLIGHT Zigbee LAN Adapter CC2652P Model SLZB-05" . --> "Update Failed: Wrong Magic Byte"

**Comment by blackie333** [comment]
Thank you for the tips. I tested "ZigStar GW Multi tool", but it was unable to find/connect with the module via IP address. Haven't tested the other tools for USB connection yet, not sure the USB port on the module is connected to zigbee chip.
According to module description USB connector is there just to supply power to the adapter (no hybrid mode mentioned). I'm also a bit afraid to use bootloader flashing tools (to not kill module web/zb functionality).

**Comment by kireque** [comment]
Follow this guide:
https://smartlight.me/diy-smart-home/slzb05-flashing

Don't forget to stop the zigbee2mqtt container, or you will get an error during connecting to the adapter.

**Comment by blackie333** [comment]
Thanks, I have tried to follow the guide but there is no "START" button on the screen, only READ, WRITE, ERASE, READ_IEEE buttons and similarly named checkboxes. Tried the READ button to backup old firmware, but "unknown error" occurred, see the screenshot
![smlight-slzb-05 Web Server](https://user-images.githubusercontent.com/22171229/170858488-15cc679c-6430-4f2c-9f6a-cf7e14cf3fe9.png)
.

**Comment by smaicloud** [comment]
Remove the port, read ieee must show the ieee in the box, check erase, write, verify and the start button appears. FW flash is successful.

**Comment by blackie333** [comment]
Thank you very much man. Had some problems with "Read IEEE" but after stopping Z2MQTT+restarting LAN the connection started to work. Flashed the f/w [20220219] successfully.

After re-starting Z2MQTT I can see that LQI value of all my routers seems way below it was with previous (12/2021) firmware.
Reported LQI value fluctuates between 29-36 (3x Philips Hue bulbs, 3x Lidl plugs, 2x OpenLumi routers), even for those which are just 5m away from the coordinator.
