### ISSUE TITLE
SBL Version of router firmware necessary 

### ISSUE THREAD

**Issue by tripplet** [Koenkk/Z-Stack-firmware#38]
I would like to use a spare CC2531 stick as a router, which was flashed with the SBL version of the coordinator firmware (by a friend), can I use the current router firmware with the SBL tool.

Will this remove the serial bootloader?

**Comment by Koenkk** [comment]
@ptvoinfo could you provide the sbl firmware?

**Comment by tripplet** [comment]
@ptvoinfo Any progress expected otherwise I'll try the alternative method to flash with an Arduino.
Just wanna know and avoid the work if possible but if you currently don't have the time its ok too.

**Comment by ptvoinfo** [comment]
@tripplet I don't have the SBL version of the router firmware yet.

**Comment by WildRat** [comment]
@ptvoinfo, could you, please share  SBL version of the router firmware?

**Comment by Jamjon** [comment]
would also be interested to change a coordinator to a router with zigpy-znp 

Is there any chance this router bin file will be available soon?
