### ISSUE TITLE
Please have old firmware versions available

### ISSUE THREAD

**Issue by gzcwnk** [Koenkk/Z-Stack-firmware#381]
I have flashed my sonoff3.0 as a router but it wont join, I have raised a bug request.   I cant prove its flashed but if I had an older firmware version I could flash it and check the logs and re-flash it and check the logs, thus proving its indeed has been flashed.

**Comment by gzcwnk** [comment]
delete this please or close it.  I just dont know how to use this web page, I found the older firmware TY.

**Comment by gzcwnk** [comment]
my error....

**Comment by gzcwnk** [comment]
Actually that's the co-ordinator firmware, I need older router firmware please.

**Comment by gzcwnk** [comment]
please put up a URL, TY

**Comment by bojanpotocnik** [comment]
https://github.com/Koenkk/Z-Stack-firmware/commits/master/router on the right side there is a _View at this point in the history_ button.
