### ISSUE TITLE
Updated sonoff to CC1352P2_CC2652P_launchpad_coordinator_20220219, can't read aquara plug consumption anymore

### ISSUE THREAD

**Issue by touzenesmy** [Koenkk/Z-Stack-firmware#382]
[SONOFF ZigBee 3.0 USB Dongle Plus, TI CC2652P Coordinator,](https://www.amazon.fr/gp/product/B09KXTCMSC/ref=ppx_yo_dt_b_asin_title_o06_s00?ie=UTF8&psc=1)

The plug is the aquara smart plug. I was able to read the power consumption before, but since I've updated, it just displays 0 watts.

Also, I had to repair all my devices after the update.

Any help/ideas ?

**Comment by TheJulianJES** [comment]
Likely related to this:
- https://github.com/zigpy/zha-device-handlers/issues/1655
- https://github.com/zigpy/zha-device-handlers/pull/1656
- https://github.com/Koenkk/zigbee-herdsman-converters/issues/1050#issuecomment-1180551212
