### ISSUE TITLE
Flashing problem

### ISSUE THREAD

**Issue by Varkzor** [Koenkk/Z-Stack-firmware#386]
I flashed my Sonoff Zigbee 3.0 Dongle with the firmware listed here.
After it is flashed successfully i understand it should generate a wifi network with TASMOTA_*** which i can't see anywhere.

Either i didn't intall it correctly, or i did something wrong along the way.
I have no idea, but i'm quite stuck in my Home Automation set-up to read the energy consumption from an Owon device.

Additional info: when flashing it with Flash Programmer 2 it says it correctly flashed the device.
How-ever i see no wifi tasmota network.
Device manager shows a Silicon Labs CP210x USB to UART Bridge (COM4)

**Comment by Koenkk** [comment]
See https://github.com/Koenkk/zigbee2mqtt/issues/13518, please don't create multiple issues.
