### ISSUE TITLE
Question: Firmwareflash

### ISSUE THREAD

**Issue by daes10** [Koenkk/Z-Stack-firmware#387]
Only a short question...

When I install a newer Firmware on my Coordinator CC26X2R1, will i be able to use my sensors further or must I pair all sensors new?

**Comment by Koenkk** [comment]
see https://www.zigbee2mqtt.io/guide/faq/#what-does-and-does-not-require-repairing-of-all-devices , note that the issues section is not meant for questions, use support channels and read the docs first next time.
