### ISSUE TITLE
Feature Request: Sniffer firmware for Sonoff Zigbee 3.0 (CC2562P)

### ISSUE THREAD

**Issue by NicolaiPetri** [Koenkk/Z-Stack-firmware#388]
Hi, 
I have bought a Sonoff Zigbee 3.0 (CC2562P based) USB stick to use as a Zigbee sniffer to troubleshoot pairing issues, unfortunately I have not been able to find a firmware that doesn't brick the device.
Would it be possible to build a sniffer version of the firmware also ?

**Comment by Koenkk** [comment]
Texas Instruments doesn't provide source code for its sniffer firmwares so I cannot provide any. If it is not included in [PACKET-SNIFFER-2](https://www.ti.com/tool/download/PACKET-SNIFFER-2/1.9.0) I suggest to ask for a fw on the e2e ti forum: https://e2e.ti.com
