### ISSUE TITLE
Not building with default firmware.patch

### ISSUE THREAD

**Issue by glentakahashi** [Koenkk/Z-Stack-firmware#39]
I couldn't get the firmware to build in a default installation of IAR + clean `git apply firmware.patch` on the dev branch. My default XDATA was 0x4D0, but I could only get it to build on 0x400. What XDATA do you build at?

**Comment by Koenkk** [comment]
Because of this I found out that I was compiling with the wrong XDATA (0x300). Fixed, thanks!
