### ISSUE TITLE
Sonoff ZBDongle-P - ZHA

### ISSUE THREAD

**Issue by parvbarot** [Koenkk/Z-Stack-firmware#392]
I've flashed my Sonoff ZBDongle-P with [CC1352P2 CC2652P launchpad router 20220125.zip] firmware. I wanted to add this to ZHA integration, but it wasn't picked up. I had flashed it numerous times, but ZHA wasn't picking it up.

**Comment by Xploder** [comment]
You've flashed the router firmware, which just works for "Repeater-Type" functionality.
You'll need to flash the coordinator firmware.

**Comment by parvbarot** [comment]
I am using sonoff zigbee bridge as coordinator and wants to use zigbee usb dongle 3.0 (CC2652P) as Router but after flashing ZHA didn't detect it.

**Comment by parvbarot** [comment]
I tried using Zigbee2Mqtt, but it didn't detect. But as a coordinator, this dongle functions perfectly.

**Comment by jerrm** [comment]
The device doesn't stay in pairing mode very long.  

Unplug the stick, place ZHA into pairing mode, then plug the stick back into power.  It should pair within a few seconds.
