### ISSUE TITLE
Flash image size exceeding flash physical size, writing canceled..

### ISSUE THREAD

**Issue by Genieplumb** [Koenkk/Z-Stack-firmware#394]
im having a problem writing the hex file to a CC2531 the file im writing via a CC Debugger tool isCC1352P2_CC2652P_launchpad_router_20220125.hex and the CC1352P2_CC2652P_other_router_20220125.hex files. 

CC debugger is green (was red before I plugged in the CC2531) 
CC2531 is also in the USB port 
OS is Mac (installed CCTool via Brew) 
Undated Brew this morning as I had a file issue. 
ive refreshed the default firmware and that works. 

I want to make the CC2531 into a Router to help the range of an installation. 

ive attached the log files for helping in this. 

please understand this is my first ever issue raised, so if ive made a silly error please excuse me  

[cc-tool.log](https://github.com/Koenkk/Z-Stack-firmware/files/9744537/cc-tool.log)

**Comment by TheJulianJES** [comment]
You're trying to flash CC262/CC1352 firmware on a CC2531 which doesn't work.

You need to flash CC2531 router firmware from https://github.com/Koenkk/Z-Stack-firmware/tree/master/router/Z-Stack_Home_1.2
