### ISSUE TITLE
Problem Compiling firmware on MacOs

### ISSUE THREAD

**Issue by pipiche38** [Koenkk/Z-Stack-firmware#395]
I'm trying to build the firmware but I'm getting

> znp_CC1352P_2_LAUNCHXL_tirtos_ticlang
> znp_CC26X2R1_LAUNCHXL_tirtos_ticlang
> znp_LP_CC2652RB_tirtos_ticlang

instead of 

> znp_CC1352P_2_LAUNCHXL_tirtos_ccs
> znp_CC26X2R1_LAUNCHXL_tirtos_ccs
> znp_LP_CC2652RB_tirtos_ccs

What do I do wrong ?

**Comment by Koenkk** [comment]
You are using a different SDK version than the instructions where written for. Assuming you are using 6.20 you can use the one from the dev branch: https://github.com/Koenkk/Z-Stack-firmware/blob/develop/coordinator/Z-Stack_3.x.0/COMPILE.md
