### ISSUE TITLE
Can you alter Vendor Product name?

### ISSUE THREAD

**Issue by sterling90x** [Koenkk/Z-Stack-firmware#399]
When updating the Sonoff Zigbee 3.0 USB gateway, the vendor product name shows up as   ID 10c4:ea60 Silicon Labs CP210x UART Bridge, can you change this?

I have an Aeotec Zwave USB Gateway with the same name.

**Comment by Koenkk** [comment]
The firmware in this repo is flashed on the Zigbee chip (CC2652P in your case). This ID comes from the UART chip which I believe is read-only, so no.
