### ISSUE TITLE
Z-Stack Version

### ISSUE THREAD

**Issue by iwl** [Koenkk/Z-Stack-firmware#40]
I can't find a version number nowhere, files, commit messages, ...
Is the repo newer then my CC2531 firmware? Z-Tool reports:

*** WARNING ***
    Expected Z-Stack version (2.7.1) does not match with actual Z-Stack version (2.6.3).  Z-Tool may not work properly.

<TX>09:32:53.42 COM5 SYS_VERSION (0x2102)

<RX>09:32:53.42 COM5 SYS_VERSION_RESPONSE (0x6102)
    TransportRev: 0x02
    Product: 0x00
    MajorRel: 0x02
    MinorRel: 0x06
    HwRev: 0x03

BTW: Is there a message reporting coordinator or router firmware?
Making that switchable by a message would also be good?

SmartRF Studio 7 doesn't find that adapter, while Z-Tool is talking to.

Are the .bin files for serial boot loading?

**Comment by Koenkk** [comment]
Z-STACK-HOME 1.2.2a is used (can be found in https://github.com/Koenkk/Z-Stack-firmware/blob/master/README.md)

`.bin` files are for serial boot loading.
