### ISSUE TITLE
Z-Stack_3.x.0 router firmware for CC2531

### ISSUE THREAD

**Issue by jmgutierrezm** [Koenkk/Z-Stack-firmware#404]
Hi All, the published Z-Stack_3.x.0 router firmware can be flashed into a CC2531?
Thanks

**Comment by bruvv** [comment]
https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/README.md Look here is a very usefull tabel..

**Comment by tom1422** [comment]
He means for the router firmware. This post might be of use: [https://github.com/Koenkk/Z-Stack-firmware/issues/153](url)

**Comment by jmgutierrezm** [comment]
Thanks bruvv, yes, the table is very useful, but if I am not wrong, it is for coordinators, not for router.
