### ISSUE TITLE
CC2530.ROUTER with CC2530_RFX2401

### ISSUE THREAD

**Issue by phoenixxie0** [Koenkk/Z-Stack-firmware#412]
Could you show something with the CC2530.ROUTER setting of PTVO?
Like this:
![image](https://user-images.githubusercontent.com/1797318/213909609-6372ecd8-3629-4e73-8737-9a04b1de445c.png)
That we don't need to save the custom converter .
THX

**Comment by ptvoinfo** [comment]
@phoenixxie0 Could you please describe your requirements a bit more? What do you want to configure?
