### ISSUE TITLE
bin version of the firmware

### ISSUE THREAD

**Issue by IlGiock** [Koenkk/Z-Stack-firmware#413]
Hy all, i'm having problems flashing my sonoff zigbee 3.0 plus-p. I found several threads about uploading the new firmware using ti flash programmer 2 solved using .bin files instead the .hex but i'm really noob and my poor english really don't help to understand how... Is there a way to have a ready bin file  of the [https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.x.0/bin/CC1352P2_CC2652P_launchpad_coordinator_20220219.zip](url). I wish it could solve the problems i'm having with my ts0601 trvs that randomly miss commands and automations...

**Comment by RubenKelevra** [comment]
@IlGiock try these:

https://github.com/Koenkk/Z-Stack-firmware/tree/6.10.01.01/coordinator/Z-Stack_3.x.0/bin
