### ISSUE TITLE
Join existing zigbee network as mqtt bridge

### ISSUE THREAD

**Issue by arnotron** [Koenkk/Z-Stack-firmware#414]
Hello,

I just purchased a Sonoff ZBDongle-E hoping to use it in parallel to my existing hue bridge. Now I have understood that currently I have to choose wether to use one or the other. 

From my understanding of the ZigBee Protocol, to run as a router the stick needs to join an existing network, which would include getting the keys. Is it maybe possible to extract this information to use it in coordinator mode?

I would be happy to learn more about the details and why I might be wrong.

**Comment by KrzysztofHajdamowicz** [comment]
You can have only one Zigbee coordinator (which is now a Philips Hue bridge).  
You can flash your Sonoff dongle to act as a router (signal repeater)
