### ISSUE TITLE
Tube's Zigbee PoE (Power Over Ethernet) Serial Coordinator (CC2652P2 variant) 20221226 Firmware update failed

### ISSUE THREAD

**Issue by WernerRH21** [Koenkk/Z-Stack-firmware#417]
![image](https://user-images.githubusercontent.com/67897090/215333267-84784f3b-fab5-4218-863a-79f9f76cd3c9.png)

**Comment by tube0013** [comment]
What are you using to flash?

Is the .hex file extracted?

**Comment by WernerRH21** [comment]
Z-Stack-firmware/CC1352P2_CC2652P_launchpad_coordinator_20221226.zip at master * Koenkk/Z-Stack-firmware (github.com)<https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.x.0/bin/CC1352P2_CC2652P_launchpad_coordinator_20221226.zip>
CC1352P2_CC2652P_launchpad_coordinator_20221226.hex


Von: tube0013 ***@***.***>
Gesendet: Sonntag, 29. Januar 2023 16:02
An: Koenkk/Z-Stack-firmware ***@***.***>
Cc: WernerRH21 ***@***.***>; Author ***@***.***>
Betreff: Re: [Koenkk/Z-Stack-firmware] Tube's Zigbee PoE (Power Over Ethernet) Serial Coordinator (CC2652P2 variant) 20221226 Firmware update failed (Issue #417)


What are you using to flash?

Is the .hex file extracted?

-

**Comment by WernerRH21** [comment]
***@***.***

Von: tube0013 ***@***.***>
Gesendet: Sonntag, 29. Januar 2023 16:02
An: Koenkk/Z-Stack-firmware ***@***.***>
Cc: WernerRH21 ***@***.***>; Author ***@***.***>
Betreff: Re: [Koenkk/Z-Stack-firmware] Tube's Zigbee PoE (Power Over Ethernet) Serial Coordinator (CC2652P2 variant) 20221226 Firmware update failed (Issue #417)


What are you using to flash?

Is the .hex file extracted?

-

**Comment by twinkie0101** [comment]
I tried to do the update today via bsl-master and receiving the following error after update starts:

`ERROR: Timeout waiting for ACK/NACK after 'Get Status (0x23)'`

I am updating the tubes coordinator (poe version) with the following file: C1352P2_CC2652P_launchpad_coordinator_20221226.hex

**Comment by tube0013** [comment]
Please open an issue on my repos for issues flashing TubesZB devises 

https://github.com/tube0013/tube_gateways
