### ISSUE TITLE
Unknown record type: 3

### ISSUE THREAD

**Issue by grannysmith59** [Koenkk/Z-Stack-firmware#428]
Tried to flash latest router firmware (CC1352P2_CC2652P_launchpad_router_20221102) to Sonoff Zigbee 3.0 dongle plus using Flash Programmer 2, but received error: Unknown record type: 3.

I was able to flash "CC1352P2_CC2652P_launchpad_router_20220125"

**Comment by rwunsch** [comment]
Could you please check: 
https://github.com/Koenkk/Z-Stack-firmware/issues/423 ?

**Comment by rwunsch** [comment]
and/or:
https://github.com/Koenkk/Z-Stack-firmware/issues/397

**Comment by Koenkk** [comment]
Duplicate of https://github.com/Koenkk/Z-Stack-firmware/issues/397
