### ISSUE TITLE
New CC2530_CC2591 coordinator firmware missing

### ISSUE THREAD

**Issue by wixoff** [Koenkk/Z-Stack-firmware#43]
Although some recent commits seem to be applicable to the CC2530 and the CC2530+CC2591 hardware, there are no coordinator firmware files in the dev branch.  The most recent file (in master) is 20190109.

Apologies if I'm missing something.

**Comment by Koenkk** [comment]
CC2530 + CC2530/CC25591 firmwares and sbl firmwares are provided once merged to master. The reason for this is that regenerating all these firmwares is a lot of work for each commit.

**Comment by wixoff** [comment]
Got it thanks.  I'll be patient!
