### ISSUE TITLE
[question] reached max device

### ISSUE THREAD

**Issue by yaniv1111** [Koenkk/Z-Stack-firmware#44]
Hi, 
I have reach the max limit of cc2531 with 18 xiaomi devices, will be possible to add anthoer Router to the  existing network without changing the  coordinator?

Thanks

**Comment by yaniv1111** [comment]
also, is it possible to replace cc2531 with normal cooridnator fw, with CC2531ZNP-Prod-44-devices.hex 
without repairing all devices?

thanks again
Yaniv

**Comment by Koenkk** [comment]
I would reflash wit the latest dev firmware (doesn't require repairing) and add a router right after that.

Not yet, there is no dev firmware available yet for the 44 devices firmware (will be when everything gets to master).
