### ISSUE TITLE
ZHA routers ceased repeating.

### ISSUE THREAD

**Issue by Aguasclaras5** [Koenkk/Z-Stack-firmware#444]
My zigbee network ZHA on Home Assistant has gone down for the 3rd time. I can not confirm the reason for the first time but for the last 2 times my 3 Sonoff routers have ceased repeating. I can reflash them like I did last time and get up and running but that is not really a solution. I have 76 devices connected ( 318 entities ). Many devices the pairing was via the Sonoff Router. Items close to the coordinator are working and a few of my Zemismart window shades that seem to have very strong routers and appear to have rerouted there link directly to the coordinator are working occasionally. The system was rock solid for the last 2 months. This is exactly the same as happened last time.
Coordinator and 3 routers are
SONOFF Zigbee 3.0 USB Dongle Plus Gateway
Coordinator firmware is from Github Koenig/ Zstack firmware 3.0 20221226

Routers are same source  3.0 20221102

Routers appear to come on line occasionally according to zigbee info for device last seen.

Device info
ti.router
by TexasInstruments
Connected via [Zigbee Coordinator](http://homeassistant.local:8123/config/devices/device/e36704aa63a9d5ad097d8df907e9e8d9)
Zigbee info
IEEE: 00:12:4b:00:29:da:eb:58
Nwk: 0x4d90
Device Type: Router
LQI: 98
RSSI: Unknown
Last Seen: 2023-04-10T13:11:04
Power Source: Mains
Quirk: zhaquirks.texasinstruments.router.TiRouter.

<img width="1663" alt="Screenshot 2023-04-10 at 2 19 20 PM" src="https://user-images.githubusercontent.com/108194955/230980005-a1784153-3e8d-4ef1-b2f2-9091606feb61.png">

**Comment by epower53** [comment]
Your routers are actually using the 1102 dev build, not the 1226 stable build. Can you upgrade one or two routers to 1226 and see if it improves the situation?
