### ISSUE TITLE
Import CCS Projects 

### ISSUE THREAD

**Issue by easterism** [Koenkk/Z-Stack-firmware#449]
Hi. According to https://github.com/Koenkk/Z-Stack-firmware/blob/develop/coordinator/Z-Stack_3.x.0/COMPILE.md i tried to import CCS Project and i've got error after Press Finish (point 5)

![image](https://github.com/Koenkk/Z-Stack-firmware/assets/2633331/702b3636-55a3-44aa-9406-f97881f45206)

OS: Debian
SDK: simplelink_cc13xx_cc26xx_sdk_7_10_00_98
CCS: 12.3.0.00005

BTW: Do you know why the link https://www.ti.com/tool/SIMPLELINK-CC13XX-CC26XX-SDK#downloads has no Download button

**Comment by w-strive** [comment]
Hi,我按照https://github.com/Koenkk/Z-Stack-firmware/blob/develop/coordinator/Z-Stack_3.x.0/COMPILE.md步骤操作，在执行git apply firmware.patch --ignore-space-change后再次重新编译，但结果出现错误，如下图
![100](https://github.com/Koenkk/Z-Stack-firmware/assets/67448018/340afa36-efaa-49bc-98f7-31eb185dbad3)

OS：   Win10Pro 19044.2965
SDK： simplelink_cc13xx_cc26xx_sdk_7_10_00_98
CCS： 12.3.0.00005
