### ISSUE TITLE
Ha does not revognize the extra router

### ISSUE THREAD

**Issue by redlingg** [Koenkk/Z-Stack-firmware#457]
Hello
I just wanted to introduce an extra router in the network. Flashing was ok with zigstar but the stick is not recognized in HA..
https://github.com/Koenkk/Z-Stack-firmware/blob/Z-Stack_3.x.0_router_20221102/router/Z-Stack_3.x.0/bin/CC1352P2_CC2652P_launchpad_router_20221102.zip

**Comment by redlingg** [comment]
ok so there is no idea at all.. Can the stick be wrong ( unusable )?

**Comment by Merril-r** [comment]
I used Zigstar to flash. After the flashing completed and the stick rebooted Z2M picked up the router straight away
