### ISSUE TITLE
Adding many AwoX 33957 light bulbs causes NWK_TABLE_FULL etc.

### ISSUE THREAD

**Issue by Jazzic** [Koenkk/Z-Stack-firmware#461]
When adding around 30 AwoX 33957 light bulbs, the pairing process starts to fail. 
Fx. these log etnries:
info  2023-06-29 17:49:44: 0xa4c138797f2233a6 (0xa4c138797f2233a6): Not supported (Unknown)
error 2023-06-29 18:51:11: Failed to read state of '0xa4c1388faadf4746' after reconnect (Read 0xa4c1388faadf4746/1 genOnOff(["onOff"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> ZDO - extRouteDisc - {"dstAddr":3631,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)')))

It seems to be a problem directly related to the number of bulbs added to the network. Everything works nicely and pairs quickly until a number of around 30 bulbs is reached. When the critical number of bulbs is reached, all subsequently added devices are recognized as not supported devices.

**Comment by Koenkk** [comment]
AwoX devices spam the network, this is already known and listed on the device pages: https://www.zigbee2mqtt.io/devices/33943_33944_33946.html#warning-degrades-network-performance
