### ISSUE TITLE
What is the current procedure for flashing the CC1352P2_CC2652P_launchpad_coordinator_20230507.zip firmware?

### ISSUE THREAD

**Issue by andregoncalvespires** [Koenkk/Z-Stack-firmware#462]
What is the current procedure for flashing the CC1352P2_CC2652P_launchpad_coordinator_20230507.zip firmware? Using bootloader mode via python with "uartlog.py" and "Smart RF Flash Programmer2" is not working. Returning the error below:

Initiate access to target: COM3 using 2-pin cJTAG.
Reading file: C:/Dongle/CC1352P2_CC2652P_launchpad_coordinator_20230507.hex.
Unknown record type: 3.
Reset target...
Reset of target successful.

I believe that this program is not capable of performing this update. Which procedure to use?

**Comment by tube0013** [comment]
see https://github.com/Koenkk/Z-Stack-firmware/issues/455

**Comment by AbeltjeNL** [comment]
I found this and worked for me:

https://github.com/Koenkk/Z-Stack-firmware/issues/397#issuecomment-1510412650

**Comment by ahd71** [comment]
I had the same issue and instead tried with https://github.com/xyzroe/ZigStarGW-MT/releases/ to flash my stick which worked great.

**Comment by KoKolaj** [comment]
I used this tutorial - https://smartlight.me/diy-smart-home/flashing_slzb-02
