### ISSUE TITLE
Programming new Version failed with TI Flashpr.2

### ISSUE THREAD

**Issue by Ledikie** [Koenkk/Z-Stack-firmware#468]
Hello,
I'm trying to program the new version "CC1352P2_CC2652P_launchpad_coordinator_20230507.hex" to RFStar module.
But it failed.
When I program the last version "CC1352P2_CC2652P_launchpad_coordinator_20221226.hex" it runs without a problem.
I tried it several time without success. My programmer Texas Smartflash2 with XDS110.

![grafik](https://github.com/Koenkk/Z-Stack-firmware/assets/81511936/a7d1b5fd-62f3-4db8-9485-a7b593d266fe)
![grafik](https://github.com/Koenkk/Z-Stack-firmware/assets/81511936/b867f454-0a8e-4cff-a099-6e562991eaa6)

**Comment by lux73** [comment]
try flashing with [python script](https://github.com/JelmerT/cc2538-bsl) as mentioned here: https://www.zigbee2mqtt.io/guide/adapters/#flashing-cc1352-cc2652-cc2538-based-adapters

works for me

**Comment by KoKolaj** [comment]
Works for me - https://smartlight.me/diy-smart-home/flashing_slzb-02

**Comment by Ledikie** [comment]
I have only the pure board (RFSTAR RF-BM-2652P2 SMA Ant.). The board is connected with 4 wires direct to my Raspi4 for operation. 2 for power supply and 2 for RX/TX.

To do the programming, I soldered 3 additional wires to the board, and connect it to the XDS110.

What I saw is the difference between the size of the 2 files:
CC1352P2_CC2652P_launchpad_coordinator_20230507.hex    498 KB new one
CC1352P2_CC2652P_launchpad_coordinator_20221226.hex    401 KB older one
Maybe this is the reason why I can’t program the new file.

**Comment by ahd71** [comment]
Several threads/issues about the same. Try another tool to flash with (I had the same)

**Comment by Ledikie** [comment]
Find a solution to program it with TI Flashprogrammer2.
Followed the instructions by this link: https://github.com/Koenkk/Z-Stack-firmware/issues/397#issuecomment-1510412650
Changed the file from ....hex into ....bin

**Comment by kgiedrius** [comment]
I got same error with 2023 firmaware, but 202212 - worked fine.
Smth wrong is with .hex file

**Comment by Koenkk** [comment]
The TI flash programmer v2 is broken, it doesn't support support the latest `.hex` files their SDK generate. There is nothing I can fix from the firmware side here. (use TI UniFlash/cc2538-bsl as an alternative).

**Comment by david-milward-r3** [comment]
It worked fine for me using hex2bin.

**Comment by kgiedrius** [comment]
TI flash program is also broken on newest windows version.

**Comment by kgiedrius** [comment]
@Koenkk  Maybe you can include .bin version of .hex file so it can be flashed with TI 2 programmer software

**Comment by lux73** [comment]
come on Guys - just use the mentioned cc2538-bsl.py Script. It works like a charm
