### ISSUE TITLE
Installed Firmware from 20230507 and  Coordinator is not working

### ISSUE THREAD

**Issue by rionshin** [Koenkk/Z-Stack-firmware#479]
Hello, 

i downloaded and installed [20230507](https://github.com/Koenkk/Z-Stack-firmware/commit/c80b77f8083f729efdf3fbac243c2d88b935ebfb) 
using:  sudo python3 cc2538-bsl.py -ewv -p /dev/ttyUSB0 --bootloader-sonoff-usb  ./CC1352P2_CC2652P_launchpad_coordinator_20230507.hex
However my Coordinator was on ttyACM0 for some reason command run  and update the firmware, however after that coordinator was moved to USB0,  Zigbee2MQQT didn't started as it was configured to be on ACM0. 
i try to revert the firmware and i am getting error:

pi@homebridge:~/cc2538-bsl $ sudo python3 cc2538-bsl.py -ewv -p /dev/ttyUSB0 --bootloader-sonoff-usb ./CC1352P2_CC2652P_launchpad_coordinator_20221226.hex
sonoff
Opening port /dev/ttyUSB0, baud 500000
Reading data from ./CC1352P2_CC2652P_launchpad_coordinator_20221226.hex
Your firmware looks like an Intel Hex file
Connecting to target...
ERROR: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

could you please let me know how i can fix this, as my home is down  :( 

Also i don't get any output :
pi@homebridge:~/cc2538-bsl $ sudo ls /dev/serial/by-id
ls: cannot access '/dev/serial/by-id': No such file or directory

When i try to update with September firmware 
pi@homebridge:~/cc2538-bsl $ sudo python3 cc2538-bsl.py -ewv -p /dev/ttyUSB0 --bootloader-sonoff-usb ./CC1352P2_CC2652P_launchpad_coordinator_20230902.hex
sonoff
Opening port /dev/ttyUSB0, baud 500000
Reading data from ./CC1352P2_CC2652P_launchpad_coordinator_20230902.hex
Your firmware looks like an Intel Hex file
Connecting to target...
ERROR: Timeout waiting for ACK/NACK after 'Synch (0x55 0x55)'

**Comment by Koenkk** [comment]
Try 202309* and provide feedback here: https://github.com/Koenkk/Z-Stack-firmware/discussions/478
