### ISSUE TITLE
Device is leaving network after just putting it pairing mode

### ISSUE THREAD

**Issue by chojnicki** [Koenkk/Z-Stack-firmware#482]
I recently switched adapter from Conbee 2 to Sonoff Dongle-P. I have wall switches (TS0001 and TS0002), but I tested same behavior on other devices like Ikea Tradfri bulbs. So when device is already paired, and I start pairing mode again on it, it just leaves network even that it was not paired to new gateway/coordinator. It makes no sense, it should keep current network if new one was not found. Sometimes I get message in Z2M "Device 'xxxxxx' left the network" and it just disappears from dashboard, but often there is no info in Z2M logs and it just stops working so that's why I'm opening this issue here.

It is easy to blame device - but most important thing is, it was NOT such issue with previous adapter. Maybe conbee did not "allowed" to leave network by device itself, and z-stack does, not sure. Previously in case of my switch, it was unresponsive for 1 minute because it was looking for new coordinator, and after that time everything was back to normal. But now I have to repair them again manually every time.
With bulbs or most devices it's not really a big issue, but with switches it is easy to put them in that pairing mode by accident, because it requires just 5 clicks to do that, which often my small kids do...

So why device is leaving me, just by putting it in pairing mode? Can I somehow disallow leaving network, or is it a bug?

I'm using firmware 20221226. I know it's not latest one, but it is considered as stable, and I did not found any fix related to my issue in changelog.

**Comment by chojnicki** [comment]
Still a issue

**Comment by jonzyk** [comment]
I switched from an Elelabs ELU013 (ezsp) to a SONOFF Dongle-P. Since I have some strange behavior with my switch, I wanted to try a recommended adapter.
I faced the same issue with 20230507
Devices already paired with my ezsp are stuck into a pairing loop. I tried several resets of the device with no effect.
New devices are paired OK.
I have seen this thread before : https://github.com/Koenkk/Z-Stack-firmware/discussions/474
So I downgraded to 20221226, and was able to pair with only 1 reset of the device.

**Comment by chojnicki** [comment]
bump to unstale

**Comment by chojnicki** [comment]
@Koenkk could you reopen this please? It's not completed :( I hate this GH bot :D

**Comment by chojnicki** [comment]
Unstale

**Comment by Koenkk** [comment]
> Can I somehow disallow leaving network, or is it a bug?

No this is not possible, to figure out what is happening I would need to have a sniff of this: https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html
