### ISSUE TITLE
CC2652RB never successfully pairs as a router

### ISSUE THREAD

**Issue by ivanfor** [Koenkk/Z-Stack-firmware#488]
Hi.
I'm trying to use a CC2652RB (Slaesh's) as a router but I'm unable to successfully pair (after flashing with 'CC2652RB_router_20221102' router firmware [here](https://github.com/Koenkk/Z-Stack-firmware/raw/Z-Stack_3.x.0_router_20221102/router/Z-Stack_3.x.0/bin/CC2652RB_router_20221102.zip)).
This is the log I always get when trying to pair:
`
Zigbee2MQTT:info  2024-01-26 14:38:57: Device '0x00124b0021cbf178' joined
Zigbee2MQTT:info  2024-01-26 14:38:57: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00124b0021cbf178","ieee_address":"0x00124b0021cbf178"},"type":"device_joined"}'
Zigbee2MQTT:info  2024-01-26 14:38:57: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x00124b0021cbf178"},"type":"device_connected"}'
Zigbee2MQTT:info  2024-01-26 14:38:57: Starting interview of '0x00124b0021cbf178'
Zigbee2MQTT:info  2024-01-26 14:38:57: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00124b0021cbf178","ieee_address":"0x00124b0021cbf178","status":"started"},"type":"device_interview"}'
Zigbee2MQTT:info  2024-01-26 14:38:57: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x00124b0021cbf178"},"type":"pairing"}'
Zigbee2MQTT:error 2024-01-26 14:42:16: Failed to interview '0x00124b0021cbf178', device has not successfully been paired
Zigbee2MQTT:info  2024-01-26 14:42:16: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00124b0021cbf178","ieee_address":"0x00124b0021cbf178","status":"failed"},"type":"device_interview"}'
Zigbee2MQTT:info  2024-01-26 14:42:16: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_failed","meta":{"friendly_name":"0x00124b0021cbf178"},"type":"pairing"}'
Zigbee2MQTT:error 2024-01-26 14:43:02: Failed to interview '0x00124b0021cbf178', device has not successfully been paired
Zigbee2MQTT:info  2024-01-26 14:43:02: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00124b0021cbf178","ieee_address":"0x00124b0021cbf178","status":"failed"},"type":"device_interview"}'
Zigbee2MQTT:info  2024-01-26 14:43:02: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_failed","meta":{"friendly_name":"0x00124b0021cbf178"},"type":"pairing"}'
`

Z2M info:
Zigbee2MQTT version [1.35.1](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.35.1) commit: [9eaaa0f](https://github.com/Koenkk/zigbee2mqtt/commit/9eaaa0f)
Coordinator type  zStack3x0
Coordinator revision 20220219
Coordinator IEEE Address 0x00124b0029e7de84
Frontend version  0.6.151
Zigbee-herdsman-converters version 18.9.0
Zigbee-herdsman version 0.30.0

Any hints?

**Comment by ivanfor** [comment]
Still an issue. Should I post it in the Z2M issues?

**Comment by McMornan** [comment]
Hi, I have the same issue ... it used to work with an older firmware version - stupid me tried to flash the latest version (router)  on my two cc2652rb sticks from slae because they kept dropping from the network ... if this the wrong place, can somebody direct me to the right place, please ? thanks!

ps: I already tried resetting the sticks ... did not work either

**Comment by snippem** [comment]
> Hi, I have the same issue ... it used to work with an older firmware version - stupid me tried to flash the latest version (router) on my two cc2652rb sticks from slae because they kept dropping from the network ... if this the wrong place, can somebody direct me to the right place, please ? thanks!
> 
> ps: I already tried resetting the sticks ... did not work either

flashed my sleah cc2652RB stick yesterday using the BSL flasing method.
But before i flashed it i allready had permit join on. The moment the flashing was done the stick joined my network.
And now works evercince did not have to push a button worked out of the box lol

just want to share my experience with this stick as a router.
