### ISSUE TITLE
Enable linking using newer IAR versions

### ISSUE THREAD

**Issue by zathras777** [Koenkk/Z-Stack-firmware#491]
While trying to build using the instructions in https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.0.x/COMPILE.md the final link failed. It turned out be related tho the issue discussed here https://e2e.ti.com/support/wireless-connectivity/zigbee-thread-group/zigbee-and-thread/f/zigbee-thread-forum/988297/cc2530-linking-issues-with-lates-iar-8051-version-released-this-monday

Adding the patch from that thread solved the issue. This should probably be added to the patch?

**Comment by Koenkk** [comment]
Feel free to make a PR!
