### ISSUE TITLE
Repairing?

### ISSUE THREAD

**Issue by GerSant** [Koenkk/Z-Stack-firmware#493]
Hi, a quick question if I proceed to update the coordinator (no change in network setting) I will have to re-pair all my devices?

Thanks in advance

**Comment by chris-1243** [comment]
What would you exactly mean by updating your coordinator ? If it is only a firmware update, no repairing required.

If you change the hardware (the coordinator), I would check this [link](https://www.zigbee2mqtt.io/guide/faq/#how-do-i-migrate-from-one-adapter-to-another).

**Comment by GerSant** [comment]
Thanks for the quick response, yes I will try to update the coordinator firmware

You can close this "Issue"

**Comment by GerSant** [comment]
Thanks!
