### ISSUE TITLE
Thread Border Router?

### ISSUE THREAD

**Issue by broyuken** [Koenkk/Z-Stack-firmware#498]
Can the zzh stick be used as a thread border router?

**Comment by Hedda** [comment]
That has nothing to do with Z-Stack, Zigbee2MQTT/Z2M, or zigbee-herdsman as this and those project are Zigbee only.

So the answer will be the same reply as to the question here -> https://github.com/Koenkk/Z-Stack-firmware/discussions/431 (summery; out-of-scope of this project but see links)
