### ISSUE TITLE
Create a firmware with LED support for the latest 20230507.

### ISSUE THREAD

**Issue by adamnet01** [Koenkk/Z-Stack-firmware#501]
Could someone create a firmware with LED support for the latest 20230507, as in this version from the link?
https://github.com/egony/cc2652p_cc1352p_RF-STAR/tree/main/firmware/coordinator
The version from the link was originally in a device with 3 LEDs.

_Originally posted by @adamnet01 in https://github.com/Koenkk/Z-Stack-firmware/issues/422#issuecomment-2096834240_

**Comment by egony** [comment]
For RF-STAR modules (and for other launchpad based) use JetHome Firmware with right LED support.

**Comment by adamnet01** [comment]
is it enough to upload the latest version? What is this patch for?

**Comment by adamnet01** [comment]
> W przypadku modułów RF-STAR (i innych opartych na starterze) użyj oprogramowania JetHome Firmware z odpowiednią obsługą diod LED. https://github.com/jethome-ru/zigbee-firmware/tree/master/ti/coordinator/cc2652

is it enough to upload the latest version: CC1352P2_CC2652P_launchpad_coordinator_20230707?
What is this patch for?

**Comment by adamnet01** [comment]
> For RF-STAR modules (and for other launchpad based) use JetHome Firmware with right LED support. https://github.com/jethome-ru/zigbee-firmware/tree/master/ti/coordinator/cc2652

is it enough to upload the latest version: CC1352P2_CC2652P_launchpad_coordinator_20230707?
What is this patch for?
