### ISSUE TITLE
Why is there never a router to router connection?

### ISSUE THREAD

**Issue by nob0dy80** [Koenkk/Z-Stack-firmware#52]
Hello,
maybe this is zigbee protocol related in general , but i wasnt able to find anything about it.

i noticed on the map,  that all router devices (lamps, power plugs) are always directly connected to the coordinator. i never see a connection between two routers, even that would make the link quality 100% better. 
A small snippet from my network map (green line is the way it should go to have a much better connection). 
![image](https://user-images.githubusercontent.com/28686079/54068251-27d8a280-424b-11e9-83db-76f4f100593d.png)

Can anyone tell me something about that? Is that zigbee-standard related?

**Comment by allofmex** [comment]
I think this can be closed, the latest iobroker network map shows sibling-links now.

**Comment by nob0dy80** [comment]
@allofmex 
closing this cause of your expirience with that..
