### ISSUE TITLE
cc2530 hex file verification 

### ISSUE THREAD

**Issue by arteck** [Koenkk/Z-Stack-firmware#56]
the new router file for cc2530 is buggy.. 
cc2531 was ok for coordinator
![grafik](https://user-images.githubusercontent.com/6681528/54145788-f4566d80-442e-11e9-8adc-1c0da87cec02.png)

**Comment by ptvoinfo** [comment]
@arteck Did you try to re-download? Many people tried the firmware, and they didn't complain.

**Comment by nob0dy80** [comment]
@arteck 
flashed it to 3 cc2530 without any problems.

**Comment by arteck** [comment]
interface = slow ..then works.. thx
