### ISSUE TITLE
Could not open specified HEX file

### ISSUE THREAD

**Issue by Smarti15** [Koenkk/Z-Stack-firmware#6]
Hi, i have download des File, but i will flash the stick und klick on button "Perform action" see the error: "Could not open specified HEX file"

https://ibb.co/cXiMkz

**Comment by arteck** [comment]
really.. you must checked out a git PROJECT ..complete.. not only one file with right mouse click..

**Comment by Smarti15** [comment]
Thanks for the tip, it worked :)
