### ISSUE TITLE
Bitron Home devices 

### ISSUE THREAD

**Issue by Smarti15** [Koenkk/Z-Stack-firmware#61]
Hello, I would like to connect the smoke detectors and the outdoor sirens of Bitron Home with the CC2531. Can you insert these devices? What information do you need?

http://bvsite.smabit.eu/index.php/produkte/smart-home-produkte/optischer-rauchmelder/
http://bvsite.smabit.eu/index.php/produkte/smart-home-produkte/aussensirene/

Many Thanks!

**Comment by JLFN** [comment]
@smarti15 you should post here https://github.com/Koenkk/zigbee2mqtt

**Comment by Smarti15** [comment]
ok thx
