### ISSUE TITLE
Firmware ZIP "Prod_20190223" not working

### ISSUE THREAD

**Issue by mf01** [Koenkk/Z-Stack-firmware#63]
The zip isn't working.

https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/CC2531/bin/CC2531ZNP-Prod_20190223.zip

**Comment by Koenkk** [comment]
whats not working?

**Comment by mf01** [comment]
The archive can't be opened.

![image](https://user-images.githubusercontent.com/1529283/54870397-771fe680-4da6-11e9-97e6-aefd00b5d1dc.png)

**Comment by Koenkk** [comment]
How did you download the file? whats the size, its working ok for me and many others.

**Comment by mf01** [comment]
I have used this link "save link as..."

Version from Jan 9 is working.
```
-rw-rw-r-- 1 markus markus 332261 Feb  6 20:15 CC2531ZNP-Prod_20190109.zip
-rw-rw-r-- 1 markus markus  73075 Mar 23 19:55 CC2531ZNP-Prod_20190223.zip

```

Just tried another way and filesize is larger ... and zip is working.

```
-rw-rw-r-- 1 markus markus 332261 Feb  6 20:15 CC2531ZNP-Prod_20190109.zip
-rw-rw-r-- 1 markus markus 332011 Mar 23 20:14 CC2531ZNP-Prod_20190223.zip

```

Think it's my fault.... sorry
