### ISSUE TITLE
Patchfile not applicable

### ISSUE THREAD

**Issue by swissbyte** [Koenkk/Z-Stack-firmware#69]
Hi

If i try to apply the latest patchfile, i get an error: 

`error: patch failed: Projects/zstack/ZMain/TI2530ZNP/OnBoard.c:24
error: Projects/zstack/ZMain/TI2530ZNP/OnBoard.c: patch does not apply`

With a pervious version of firmware.patch, everything worked as expected

**Comment by antst** [comment]
Same here, if I apply latest patch from dev branch, it doesn't work.
The only way to apply patch is to add --ignore-space-change option.

**Comment by Koenkk** [comment]
You indeed need to use the `--ignore-space-change option` option.
