### ISSUE TITLE
CC2530+CC2592 patch

### ISSUE THREAD

**Issue by kirovilya** [Koenkk/Z-Stack-firmware#71]
Hi, Koen.
I can not make proper PR to your firmware patch, but I have make patch to my-repo and get patch from it. Can you make correction to code for coordinator on Z-Stack 1.2.2 based on this patch ?
[cc2592-znp.zip](https://github.com/Koenkk/Z-Stack-firmware/files/3100543/cc2592-znp.zip)

It is for https://github.com/Koenkk/zigbee2mqtt/issues/1437 issue.

**Comment by Koenkk** [comment]
This patch has quite a big diff from the current `firmware.patch`, how to apply it?

**Comment by kirovilya** [comment]
I think - manually. It is not so much if look at file:
![изображение](https://user-images.githubusercontent.com/8360230/56498225-71363600-6509-11e9-8a7e-01b9f0837d01.png)

In one of the files - preinclude.h so many changes in patch, but in fact it is:
![изображение](https://user-images.githubusercontent.com/8360230/56498171-4815a580-6509-11e9-806a-2d1ec272be7e.png)

**Comment by kirovilya** [comment]
Ok. I tried again [0001-cc2592.zip](https://github.com/Koenkk/Z-Stack-firmware/files/3108861/0001-cc2592.zip)

**Comment by Koenkk** [comment]
That worked! Firmware: https://github.com/Koenkk/Z-Stack-firmware/tree/dev/coordinator/Z-Stack_Home_1.2/max_stability/CC2530_CC2592

**Comment by kirovilya** [comment]
Thank you!
