### ISSUE TITLE
CC2530(+CC2591) max_devices version of FW

### ISSUE THREAD

**Issue by antst** [Koenkk/Z-Stack-firmware#73]
There  is no max_devices version of firmware for cc2530 and for cc2530+cc2591.
Is it possible to add those?

**Comment by Koenkk** [comment]
I prefer not to:
- The max devices firmware is a workaround, it will perform much less with bigger networks. Instead you should add more routers to your network.
- Maintaining/generating all these firmware's each time on an update is very time consuming for me
