### ISSUE TITLE
CC2531 router has a very long device name 

### ISSUE THREAD

**Issue by james-fry** [Koenkk/Z-Stack-firmware#77]
The name for my cc2531 routers flashed with [this f/w](https://github.com/Koenkk/Z-Stack-firmware/blob/master/router/CC2531/bin/CC2531_router_2018_09.zip) is very long:

> [CC2530 router](http://ptvo.info/cc2530-based-zigbee-coordinator-and-router-112/) (CC2530.ROUTER)

This is causing network map to get "corrupted", where the routers are very wide due to the name and other entities overprint:

![image](https://user-images.githubusercontent.com/5823294/56760804-de5cfc00-6793-11e9-9864-cd9b38a7ce6a.png)

Also it incorrectly states cc2530 rather than cc2531.

Obviously this is not a high priority defect, but next time a new bin is compiled please consider to fix these...

**Comment by ptvoinfo** [comment]
@james-fry This problem is related to drawing, but not the router name in the firmware.

**Comment by Koenkk** [comment]
@ptvoinfo yes that's one problem, the other problem is that the CC2530 router firmware has the same model as the CC2531 router firmware, therefore they cannot be distinguished.

**Comment by james-fry** [comment]
> @james-fry This problem is related to drawing, but not the router name in the firmware.

@ptvoinfo I agree - the renderer for the map should handle a long name.
But I dont agree that the name needs to be that long.
> CC2531 Router
would be fine.
Even with a URL shortened link, maybe.
But no need for the length we see with the token "CC2530 router" there twice.
"[CC2530 router](http://ptvo.info/cc2530-based-zigbee-coordinator-and-router-112/) (CC2530.ROUTER)"

**Comment by Koenkk** [comment]
@james-fry this long name has nothing to do with @ptvoinfo firmware, but is a zigbee2mqtt bug.

**Comment by james-fry** [comment]
> is a zigbee2mqtt bug.

Ah OK. Thx for letting me know.
Either way, all these are minor issues.
