### ISSUE TITLE
router cc2531 does not connect

### ISSUE THREAD

**Issue by salopette** [Koenkk/Z-Stack-firmware#78]
Hallo, I flashed a cc2531 with router-cc2531-diag, but the red lamp flashes all the time only.
I see in zigbee2mqtt log synonymous nothing that a router has connected.

**Comment by zibous** [comment]
Same problem here, when i flash the router-cc2531-std.hex:

Erase and flash the CC2531 works, so i hope :)
Press ** S2** - Short single press, but nothing happens - I see in zigbee2mqtt log synonymous nothing that a router has connected.

```
> cd flash_cc2531
> ./cc_chipid
 --->  ID = b524.

> cd ~/flash_cc2531  
> wget https://github.com/Koenkk/Z-Stack-firmware/raw/master/router/CC2531/bin/CC2531_router_2018_09.zip
> unzip CC2531_router_2018_09.zip 

## Erase and flash the CC2531 
> ./cc_erase
> ./cc_write router-cc2531-std.hex

[...]
ID = b524.
  reading line 12160.
  file loaded (12168 lines read).
writing page  96/ 96.
verifying page  96/ 96.
 flash OK.
[...]
```
sudo journalctl -u zigbee2mqtt.service -f

```
Jul 16 16:26:49 rb3 systemd[1]: Started zigbee2mqtt.
Jul 16 16:26:53 rb3 node[17777]:   zigbee2mqtt:warn 7/16/2019, 4:26:53 PM `permit_join` set to  `true` in configuration.yaml.
Jul 16 16:26:53 rb3 node[17777]:   zigbee2mqtt:warn 7/16/2019, 4:26:53 PM Allowing new devices to join.
Jul 16 16:26:53 rb3 node[17777]:   zigbee2mqtt:warn 7/16/2019, 4:26:53 PM Set `permit_join` to `false` once you joined all devices.
Jul 18 11:36:44 rb3 systemd[1]: Stopping zigbee2mqtt...
Jul 18 11:36:44 rb3 systemd[1]: Stopped zigbee2mqtt.
Jul 18 11:36:44 rb3 systemd[1]: Started zigbee2mqtt.
Jul 18 11:36:49 rb3 node[19622]:   zigbee2mqtt:warn 7/18/2019, 11:36:49 AM `permit_join` set to  `true` in configuration.yaml.
Jul 18 11:36:49 rb3 node[19622]:   zigbee2mqtt:warn 7/18/2019, 11:36:49 AM Allowing new devices to join.
Jul 18 11:36:49 rb3 node[19622]:   zigbee2mqtt:warn 7/18/2019, 11:36:49 AM Set `permit_join` to `false` once you joined all devices.
.....
```
![ziggemap](https://user-images.githubusercontent.com/30198737/61450340-29cc1400-a957-11e9-9b4e-2332cbee5d9b.png)

**Comment by abmantis** [comment]
Also having this issue when trying to pair with ZHA. Any tips?

**Comment by zibous** [comment]
@abmantis 

I bought OSRAM Smart + plug's and now use them as a router. These have a greater range and it works with connecting to the coordinator and the other zigbee devices (Aqara door, temp, waterleak, motion devices)

**Comment by abmantis** [comment]
So, after leaving the network open for a lot of time (like 15 minutes), it finally joined!

**Comment by cconde** [comment]
I'm having the same problem, Is th 15 minutes a common solution?

**Comment by cconde** [comment]
Seems waiting is not a solution for me... Unable to connect so far

**Comment by ptvoinfo** [comment]
@cconde If you cannot pair the CC2530 router:
1. Ensure that only one network around accepts joining. 
2. Move the outer closely to the coordinator ~1m.
3. Power on the router, wait 2 seconds, power off. Repeat this cycle three times (this producedure makes full reset).

**Comment by cconde** [comment]
Done all three unsuccessfully.

Zigbee sniffing shows coordinator sends an join successful packet and the transport key and at that point router reboots and tries again to join.
I'm suspecting router can't decode Transport Key properly as Philips encodes it with a non standard Commissioning Key.
