### ISSUE TITLE
coordinator max_devices for other devices

### ISSUE THREAD

**Issue by dzungpv** [Koenkk/Z-Stack-firmware#81]
@Koenkk  could you provide max_devices device for other device like CC2530, CC2530+CC2591/CC2592

**Comment by aodro** [comment]
Hi!
It would be nice to have max_device versions for CC2530 flavours, as the CC2531 has issues with xiaomi devices through routers (https://github.com/settings/sessions/authentications/291973754) and the coverage is not that good.
I read that you preffer not to, but, please do :)

**Comment by Koenkk** [comment]
With the release of zigbee2mqtt 1.4 (soon), there will be only one firmware per device. This firmware supports 25 devices. See https://github.com/Koenkk/Z-Stack-firmware/tree/dev/coordinator

**Comment by dzungpv** [comment]
@Koenkk thank you
