### ISSUE TITLE
Max real devices with version 1.4.0 and firmware version 20190513

### ISSUE THREAD

**Issue by orxaz** [Koenkk/Z-Stack-firmware#83]
Hi.

Just reading the notes on new zigbee2mqtt version, them say that max devices are 45 adding a CC253x router.

Then, if I have some routers like Ikea bulbs, but no CC253x ones, will I not be able to use more than 45 devices?

I have exacly 50 devices right now, but none of them is a CC253x router. I am afraid to flash new version if I will not be able to manage all devices.

Thanks!

**Comment by Koenkk** [comment]
If you have plenty of routers (IKEA bulbs, etc.) you probably have nothing to worry about, note that you can always revert.

**Comment by orxaz** [comment]
Ok Koen, I'll give it a try ASAP.

Thanks for your reply!
