### ISSUE TITLE
Which router to use with new unified coordinator

### ISSUE THREAD

**Issue by sascha777** [Koenkk/Z-Stack-firmware#84]
Hi @Koenkk 
I have one coordinator and two routers running in my network. 
Which router firmware would you recommend for the new CC2530_CC2591_20190513 coordinator?

**Comment by sascha777** [comment]
Or does „unify“ mean that the new firmware can also be used for the routers?

**Comment by Koenkk** [comment]
- This is a coordinator firmware, cannot be used for routers
- Router firmwares can be found here: https://github.com/Koenkk/Z-Stack-firmware/tree/master/router

**Comment by sascha777** [comment]
Thanks 👍🏼
