### ISSUE TITLE
CC2652R 20190426 - Questions

### ISSUE THREAD

**Issue by JustinHoeky** [Koenkk/Z-Stack-firmware#85]
Hi there,

Can someone tell me what the device-limit is on this firmware/device?
Look really promising, so i would like to try it since it's only 30$

Will it be recommended to switch from a CC2531 to a LAUNCHXL-CC2652R board right now?

**Comment by Koenkk** [comment]
No, the CC2652R is not stable yet. See https://github.com/Koenkk/zigbee2mqtt/issues/1429
