### ISSUE TITLE
Z-Stack 3.0 for CC2530

### ISSUE THREAD

**Issue by jiki974** [Koenkk/Z-Stack-firmware#89]
Please, can you provide instructions for building Z-Stack 3.0 for CC2530?

**Comment by Koenkk** [comment]
Available now: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.0.x/bin can you let me know if it works?

**Comment by jiki974** [comment]
Thank you so much for your incredible work ! It works fine but sometimes I need to restart my CC2530 board in order to made it work. However I have a problem with zigbee green power devices, their didn't appears ... I thought that Zigbee 3.0 is compatible with Zigbee green power.

**Comment by Koenkk** [comment]
Yes it is, but some additional things are needed to support this (green power commissioning).

**Comment by jiki974** [comment]
Great reactivity thank you !
