### ISSUE TITLE
Request for bin file for sbl_tool.

### ISSUE THREAD

**Issue by realwax** [Koenkk/Z-Stack-firmware#90]
Hi,

I kindly like to ask for the bin file to be contained in the binary folder of each plattform for a direct use of sbl_tool. With HEX files it doesnt not seem to work. Bin does...
Would be great. Or is there a simple way to convert it? hex2bin? settings?

Thank you
Kind regards

Wolfgang

**Comment by Koenkk** [comment]
Added, Z-Stack 3 will be added later.
