### ISSUE TITLE
DL-22 module (CC2530 + CC2591) support

### ISSUE THREAD

**Issue by AndrewLinden** [Koenkk/Z-Stack-firmware#92]
Please consider making compiled firmware versions for the DL-22 module.
This module has different pin connections between CC2530 and CC2591: https://github.com/Koenkk/zigbee2mqtt/issues/1362#issuecomment-483133324

**Comment by Koenkk** [comment]
Seems to be the same as https://github.com/Koenkk/zigbee2mqtt/issues/1362#issuecomment-499349018
