### ISSUE TITLE
programming compiling 8051Z-stack Home 1.2.2a

### ISSUE THREAD

**Issue by mquinn123** [Koenkk/Z-Stack-firmware#95]
What are you using to program/compile 8051 soc for cc2531/cc2530 with Z-stack home 1.2.2a.  The new IAR doesn't support this anymore only Z-stack 3.0.  I think Z-stack Home 1.2.2a readme says you need IAR 9.03 to compile.  And they don't even offer a evaluation of this version anymore. 

I have a cc2530 dev board that I want to program to control I/O to a 8ch relay and separate momentary switch.  It's in the supported devices under dnckatsw00x, but the hex is only given for a single relay.  

It would also be good to program for simple sensor inputs, temperature etc.  Just manipulating the Z-stack home examples.

I think I already know the answer that you have to buy IAR software, but its a bit much to drop thousands on project, pretty frustrating, kind of kills dev for this board.

**Comment by Koenkk** [comment]
What errors do you get when compiling with the latest IAR?
