### ISSUE TITLE
CC2530 + CC2592 + Z-Shepard power mode

### ISSUE THREAD

**Issue by dikuznet** [Koenkk/Z-Stack-firmware#99]
CC2530 + CC2592 + Z-Shepard. How to transfer the coordinator to the maximum power mode? Is this possible without recompiling the firmware? Thank you in advance!

**Comment by ptvoinfo** [comment]
@dikuznet The coordinator sets the maximum power mode automatically.

**Comment by a-bailey** [comment]
is it possible to reduce the maximum power since I read in another issue that the full power(20 dbm?) is illegal where I live (Germany)

**Comment by ptvoinfo** [comment]
The max power is 100mW. 20 is not dbm.
